lib/marked.js
allowing dot before extension as github markdown
```.md
```.ext
some code
```
```
=> allowing dot before extension

lib/marked.js
This allows the rendering of text nodes to be overwritten. I've found this particularly useful in cases where I needed to escape certain character sequences in all text nodes.
=> Added support for manual text node rendering

Gulpfile.js, package.json
This currently just handles updating marked.min.js (so we don't have to do things like #548), but Gulp allows for more functionality to be added over time.
=> Add a Gulpfile

bower.json
Hey, while installing the package with Bower I noticed that package version was not updated in Bower file  (according to GitHub releases page and npmjs registry, now it is 0.3.3, while bower addresses 0.3.2). So this PR fixes this.
=> Correct version in bower.json

lib/marked.js, man/marked.1
Hello,
I write my email newsletters in Markdown and I don't want email addresses to be mangled (I think spam filters will have trouble with the mangling), so I introduced -mangle/-no-mangle option (-mangle is default).
Would you consider this for inclusion?
(Warning: no tests, could someone give me a hand on writing a test?)
=> Add -mangle/-no-mangle to enable/disable mangling of email addresses.

lib/marked.js, test/tests/text.smartypants.html, test/tests/text.smartypants.text
Hi,
according to [Gruber's
Smartypants](http://daringfireball.net/projects/smartypants/)
`--` result in an `&ndash;`(\u2013) and `---` in an `&mdash;`(\u2n14).
As far as I can tell, `marked` converts `--` into `&mdash;`
=> Smartypants &ndash and &mdash

lib/marked.js, test/new/gfm_hashtag.gfm.html, test/new/gfm_hashtag.gfm.text, test/new/gfm_hashtag.nogfm.html, test/new/gfm_hashtag.nogfm.text, test/tests/gfm_hashtag.gfm.html, test/tests/gfm_hashtag.gfm.text, test/tests/gfm_hashtag.nogfm.html, test/tests/gfm_hashtag.nogfm.text
Do not encode `#hashtag` (no white space) at GFM mode.
=> Fix to heading regular expression for GFM #201.

lib/marked.js, test/tests/gfm_code.html, test/tests/gfm_code.text
Fixes #615 
There's another test failing (def_blocks), but it was also failing before this fix.
=> Fixed parsing of empty code blocks.

README.md
Changed sanitize default from true to false in the example.
=> Update readme example to reflect defaults

README.md
The text in the README implies that the default options are being shown, but the default option for sanitize is "false". Showing "true" could mistakenly lead a user to assume that they don't need to enable the sanitize option.
=> Use the correct default value for "sanitize" in the README example code

README.md
Benchmarks are now below the old `above` reference.
Remove it to avoid future problems in case sections move around again.
=> Typo benchmarks are below reference in README.

test/tests/links_reference_style.html, test/tests/links_reference_style.text
this is how it should work according to CommonMark
=> add a test case for links defs & paragraphs

lib/marked.js
Recent changes broke IE8 support. This makes things compatible with old regex engines (in IE8, old Safari and old Opera).
More information: https://stackoverflow.com/questions/10843428/what-is-meaning-of-in-javascript-regexps/10843677#10843677
=> Support older regex engines

lib/marked.js
Fix for https://github.com/chjj/marked/issues/990
These two variables are undeclared and throw an error in strict mode.
=> Declare undeclared variables

lib/marked.js, test/tests/gfm_links_invalid.sanitize.html, test/tests/gfm_links_invalid.sanitize.text, test/tests/links.sanitize.html
**TL;DR:** Leaves link text but removes hyperlink.
Currently when there is a link that either cannot be parsed, or is detected to be potentially malicious, **marked** simply hides the entire link. For example, if I had the following markdown:
```
For help: [Click Here](data:text/html,lkjasdjflkasd==).
```
the output would be the following:
> For help: .
_This is especially problematic_ when URLs are automatically converted to links. For example:
```
http://example.com
```
Would automatically become:
> http://example.com
If for some reason the URL cannot be parsed, then the URL simply does not display at all. This happens if it has un-urlencoded characters etc., or if it otherwise cannot be parsed, but _was_ identified as a URL by the separate lexer.
=> Make erroneous / dangerous links display as text only

package-lock.json, package.json, test/index.js
Sorting tests alphabetically for more deterministic tests.
@joshbruce this was supposed to go with #1002
=> sort tests

lib/marked.js, test/new/def_blocks.html, test/new/toplevel_paragraphs.html, test/new/toplevel_paragraphs.md
See https://github.com/chjj/marked/issues/1006
=> Revert 98ac7a4 and a477d1d

Makefile, bin/marked, man/marked.1.txt
This fixes #992, at least temporarily.
See also #994
I've parsed the manpage in order to generate a textual version stripped of any escape characters. Whenever `--help` is called and `man` cannot be run, it simply prints this textual version on the screen, as suggested by @UziTech [here](https://github.com/chjj/marked/pull/994#issuecomment-355573220).
=> Print help without `man`

lib/marked.js, test/new/gfm_code.html, test/new/gfm_code.md
This fixes #645 and fixes #931.
Preserve trailing newlines in code fence per [commonmark spec](http://spec.commonmark.org/0.28/#example-98).
~~~markdown
```js
ciao();
```
~~~
becomes
~~~html
<pre><code class="lang-js">ciao();
</code></pre>
~~~
This includes tests, which are not useful since whitespace is not checked for in our test routine. (Might need to fix this too)
=> Preserve trailing newlines in code fences

lib/marked.js, test/new/headings-id.html, test/new/headings-id.md, test/new/links_reference_style.html
PR for #450
I hope it doesn't seem overkilling, I kept it as small as possible.
Comments are welcome. I'll be posting some tests, if I can manage to make them work.
Meanwhile I tested it with
``` markdown
(which doesn't really make any difference, here)
```
and I got
``` html
<h3 id="heading-with-a-link">Heading with a <a href="http://github.com/">link</a></h3>
<h3 id="heading-with-some-italic-text">Heading with some <em>italic text</em></h3>
<h3 id="or-some-strong">Or some <strong>strong</strong></h3>
<p>(which doesn&#39;t really make any difference, here)</p>
<h3 id="or-even-code">Or even <code>code</code></h3>
<h3 id="what-about-strikethrough">What about <del>strikethrough</del></h3>
```
which looks good to me.
Fixes #450, fixes #510
=> IDs of headings with inline tokens (link, em, bold...)

lib/marked.js, test/new/cm_blockquotes.html, test/new/cm_blockquotes.md, test/new/def_blocks.html, test/new/def_blocks.md, test/new/toplevel_paragraphs.html, test/new/toplevel_paragraphs.md
I've made blockquotes (almost 100%) compliant with the commonmark [spec], and added the related test cases, from the spec itself. They all pass, but I was not able to pass example 198 and 200 because they are related to list and code fences rules. This will need to be fixed in the future if anyone's up to it.
Many thanks to @KostyaTretyak who helped in solving related issues before
[spec]: http://spec.commonmark.org/0.28/#block-quotes
=> [commonmark] Make blockquotes commonmark compliant

lib/marked.js
I agree with what @scottgonzalez said here: https://github.com/chjj/marked/issues/417#issuecomment-42740178
I chose to return `null` instead of an empty string in order to let the user know there's a problem, and that it's probably his fault.
The `TypeError` is still thrown if a user calls manually `Lexer.lex` and then `Parser.parse`, but I think it's her/his business at this point.
fixes #168 fixes #417 fixes #447 fixes #291 fixes #442 fixes #635 fixes #658
fixes #681 fixes #755 fixes #758 fixes #776 fixes #787 fixes #794 fixes #802
fixes #934 fixes #867 fixes #903 fixes #955 fixes #1021
=> Throw error on non-string input

test/new/cm_link_defs.html
As explained [here](https://github.com/chjj/marked/pull/682#issuecomment-359208055) a failing test was introduced in #1018 as a result from merging #456. This pr fixes it.
=> Fix failing case

lib/marked.js
As I explained [here](https://github.com/chjj/marked/pull/1018#issuecomment-359207001):
With the new commonmark compliant rule for link definitions, literal (matched) doubles quotes in titles are not supported anymore, so this legacy test from markdown.pl failed. I re-added support for this (even if it is against the cm spec).
Backslash-escaped (non-matching) quotes are still supported.
I did not consider it worth to create a separate `pedantic` rule for this.
(pedantic means it is going to replicate markdown.pl behavior exactly)
=> Make legacy test literal_quotes_in_titles pass

.gitattributes
GitHub shows marked as HTML when in fact, it is a JS project.
This adds an [override](https://github.com/github/linguist#overrides) so the test folder is ignored when detecting the primary language because that is where all the html lives.
=> Fix GitHub language via override

package.json
We recently moved the github repo from `chjj` to the `markedjs` org.
This fixes the npm `package.json` to point to the new URL.
=> Update package.json to new GitHub repo

package-lock.json, package.json
Something seems odd. The `.min` didn't seem to change. Also, not running from a fork, and I should be...sorry.
=> Release 0.3.15

.github/PULL_REQUEST_TEMPLATE.md, RELEASE.md, package.json
1. Decided to go with `preversion` instead of anything related t publish...version only update the `package.json` file, which needs to be committed anyway; so, thinking anything that needs to be updated and part of a commit should be able to tag along.
2. Created RELEASE.md for instructions on building a release.
This gives us a three step process when we don't include the setup things - and makes us completely within NPM commands:
1. `npm test`
2. `npm version [major|minor|patch]`
3. `npm publish`
Replaces #1064
- Tests 
??
=> Publish sequence update

test/index.js
Problem:
On hangs, test output is hard to read.
Solution:
Print test name before starting.
Bonus:
Also print an approximation of how long each test takes to run.
Fixes #1084.
- Tests 
@joshbruce @UziTech
=> test: pretty test output

.travis.yml, package.json
Tell travis-ci to check for linting errors instead of fixing them.
- Tests 
??
=> test lint instead of fixing it in travis

test/index.js
#1085 introduced tabs not spaces to `index.js`.
#1086 introduced testing the lint in Travis, not fixing it.
Therefore, Travis fails.
Recommend merging this and #1082 to minimize future occurrences.
=> Switched out tabs for spaces

.github/PULL_REQUEST_TEMPLATE/release.md, CONTRIBUTING.md
**Marked version:** 0.3.17
See [comment](https://github.com/markedjs/marked/issues/1097#issuecomment-369282046) from @intcreator for context.
> Perhaps we can make clear which version of the spec each version of Marked adheres to so if people want compatibility available in a certain version of the spec they can use the corresponding version of Marked? Potentially even syncing Marked versioning to the spec in some way?
=> Update release template

README.md
**Marked version:** 0.3.17
Recommendation from @davisjam via [comment](https://github.com/markedjs/marked/pull/1083#issuecomment-368924985) on #1083 seemed like a good one to me and more in keeping with standard operating procedures within the broader open source community regarding reporting and resolution of security issues (thanks for the education). Modified language to use "committers" and explicitly call out NPM owners.
Right now @chjj and I get all the security-related emails because we are the listed owners of the package in NPM. Having said that, I'm not sure there's much he and I are able to actually _do_ to resolve them (for various reasons). 
Might be nice to add emails (or something) for the committers on the AUTHORS page (see …
=> Update security section of README

package.json
See #1083
PR runs lint tests along with test suite...locally.
=> Run lint tests with regular test suite

.editorconfig
**Marked version:** 0.3.16
**Proposal type:** project operations
Tabs are rendered as literal tab characters, not spaces using Sublime Text 3.
Was working on #1076 and noticed the code samples were rendering funny when it came to whitespace and text wrapping. Realized it was because my editor was using literal tabs instead of spaces.
A `.editorconfig` file following similar rules as lint options...specifically, spaces not tabs.
See also http://editorconfig.org
Could be accepted before or after #1076
=> Setup .editorconfig

AUTHORS.md
**Marked version:** 0.3.17
This PR:
- Adds limits to each contributor type size starting with committer.
- Makes explicit the concept of volunteering for a change in status to become more engaged.
=>  Add size constraints and ability to volunteer to AUTHORS

.travis.yml, test/index.js
**Marked version:** 76d75e19c7717e954c91a4a4c4c6499aa5f7b20a
Adds [build stages](https://docs.travis-ci.com/user/build-stages/) to travis-ci to make it easier to see what failed.
=> travis build stages

.eslintrc.json, jasmine.json, package-lock.json, package.json, test/integration/marked-spec.js, test/specs/specs-spec.js, test/unit/marked-spec.js
**Marked version:** latest
Adds Jasmine for unit and integration testing
Fixes #1103
=> [WIP] Jasmine 3.1.0

.editorconfig
**Marked version:** 0.3.17
tl;dr: PR changes editorconfig to use tabs not spaces while still ignoring MD files in test directory.
Looking at the CommonMark specification and considering the future regarding #1104 and https://github.com/markedjs/marked/issues/1103#issuecomment-369957173 a lot of the examples use honest tabs...not spaces in Markdown...makes sense given the nature of plain text editors (this was why @davisjam's initial contributions didn't pass lint - he uses VIM, which doesn't do spaced tabs).
So, not too sure what to do here regarding ignoring that `/test` folder. Or maybe ignoring markdown files all together like Federico had mentioned in the initial PR #1082 - think I forgot to put it back into WIP status or something and we hadn't really talked more about the GH Pages …
=> [editorconfig]: All md files except in test use tab

package-lock.json, package.json
=> Release 0.3.18

docs/README.md, docs/index.html
**Marked version:** latest
This PR adds a ribbon that links to the github repo and adds a link to marked icon back to the README.md
=> Docs navigation

docs/CODE_OF_CONDUCT.md
I've also tried to shorten the text part of the second link to not be a bit tautological.
=> Fix unrendered links in docs/CODE_OF_CONDUCT.md

docs/USING_PRO.md
* Rename undefined variable.
* Delete unneeded quotes.
* Fix alignment in the actual output from the code example and make it more close to the "Output:" example (otherwise, the indentation of the "<h1>" line will be out of order).
=> Fix nits in code example in USING_PRO.md

docs/USING_ADVANCED.md
* Add some missing defaults ([ref](https://github.com/markedjs/marked/blob/84c5bc75ee458ce6aa6d71694e03351ebe1fee30/lib/marked.js#L1344-L1361)).
* Add periods.
* Simplify spaces.
=> Complement options table in USING_ADVANCED.md

docs/CODE_OF_CONDUCT.md, docs/CONTRIBUTING.md, docs/PUBLISHING.md, docs/README.md, docs/index.html
- Fixes linking in docs
- Fixes #1166
- Fixes #1167
=> Hash change docs

docs/demo/demo.js, docs/demo/index.html
-  Adds outputType to the demo query string
This will allow linking to a demo and automatically showing a section other than the preview.
=> Demo link outputtype

bin/marked, docs/README.md, test/unit/marked-spec.js
**Marked version:** 84894118873d616c085f216a2d818c761f0592be
Allow marked to use a string argument as input.
```sh
$ marked --string "*test*"
<p><em>test</em></p>
$ marked -s "*test*"
<p><em>test</em></p>
```
=> allow string arg from command line

lib/marked.js
- Sets the Renderer options to the default options by default
I'm not sure if there is a reason the Renderer options were set to an empty object instead of the default options. The Parser and Lexers are set to the default options already
```js
function Renderer(options) {
this.options = options || {};
...
```
```js
function Lexer(options) {
this.options = options || marked.defaults;
...
```
```js
function InlineLexer(links, options) {
this.options = options || marked.defaults;
...
```
```js
function Parser(options) {
this.options = options || marked.defaults;
...
```
=> use default options in Renderer by default

README.md, docs/README.md, test/unit/marked-spec.js
The second bullet was just long to read, think we can get the point across while maintaining the spirit.
=> Get second marked descriptor to fit one line

README.md
🌶 Spice up the readme with emoji and logo
=> Update readme with emoji

lib/marked.js, test/helpers/helpers.js
- add function `marked.getDefaults()` that gets assigned to `marked.defaults`
- resets the defaults before each test
=> Reset defaults before tests

.travis.yml
**Marked version:** latest
This adds separate build stages for unit, spec, and integration tests as well as a minify build step which is only run when the master branch is pushed to.
The minify build step requires a github token be stored on travis (this should be done securely) and only given `public_repo` access
I'm not sure what we want to do with the different node versions. I don't think we need to run all tests against all node versions.
Later we can add a browser test stage.
=> More build stages

test/index.js
- Shows which tests are failing because of taking too long like in #1226 
=> show failing test when original tests takes > 1s

docs/AUTHORS.md
Technically this makes me a Contributor according to GH ;) LOL j/k I do what I can when I can. :)
0.3.19
GitHub Flavored Markdown *(Perhaps CommonMark down the line)*
- Fixes the request at https://github.com/markedjs/marked/issues/1232#issuecomment-382747699 
GitHub Flavoured Markdown of course.
Continued, awesome, markdown for > ~9437 users ... denoted.
A subtle, indirect, request for Usership addition in a comment. :) Hopefully I got the badge of honour correct.
=> Add self from OUJS Organization to AUTHORS.md

docs/AUTHORS.md
* Unfortunately @joshbruce lost some credibility by a post edit with an edit misusing the OpenUserJS brand so respectfully removing listing.
NOTE:
* This is probably why no-one else has done this
Ref:
* #1233
with
> LGTM!
... apparently it wasn't and shouldn't have been merged without all parties consent.
=> Withdraw permission for Branding usage

lib/marked.js, test/specs/gfm/gfm-spec.js
This PR adds support for escaped pipes inside GFM tables.  `\|` can be used to embed a literal pipe inside a table cell.
- Fixes [1237](https://github.com/markedjs/marked/issues/1237)
This means compliance with GFM spec example #193.
=> Escapedpipes

docs/PUBLISHING.md
The description of the zero-major is no longer accurate. This verbiage should be relatively future proof.
=> Remove publishing details

lib/marked.js, test/new/gfm_tables.html, test/specs/gfm/gfm-spec.js, test/specs/gfm/gfm.0.28.json
**Markdown flavor:**  GitHub Flavored Markdown
This PR introduces full compliance with GFM tables. (I think)  I'm new here, and this is a somewhat bigger code change.  Despite my best efforts, I may have messed something up, so feedback is welcome.
The gfm_tables tests cover this functionality.
=> Gfm tables

docs/USING_ADVANCED.md
This adds a couple missing option types to the docs and also shows the version introduced for `headerIds`.
- Related #1208
=> Update advanced usage docs

lib/marked.js
**Marked version:** 41a8cad4aa23ba96a4da2aee99a511b94dcc8771
- Amendment to #1248 following the comments from https://github.com/markedjs/marked/issues/1247#issuecomment-386022022
=> fix paragraph

.travis.yml
**Markdown flavor:** 7a9e35eb7d5afc729cf73a6a7c5d9bfbe7a833c1
- Allows travis to pass even when `npm run test:redos` fails
closes #1254
=> Allow travis to pass when redos check fails

lib/marked.js, test/specs/gfm/gfm-spec.js, test/specs/gfm/gfm.0.28.json
**Marked version:**  0.3.19
**Markdown flavor:**  GitHub Flavored Markdown
Fixes #107
Fixes #419
Fixes #170
Fixes #689
Fixes #587
This adds [task list items](https://github.github.com/gfm/#task-list-items-extension-) support as specified in GFM.  These are the checkboxes you can make in bulleted lists.
I did do some funny stuff in the gfm test runner.  In particular all the other gfm tests use the xhtml rendering option.  But for some reason, (probably not a good one) the checkbox rendering in the gfm spec is *not* xhtml.  So, I added a an `xhtml` attribute to the test spec json for those tests.  It seems pretty janky.  Maybe someone can think of a better way of handling it.
=> GFM compliance for tasks lists

docs/USING_ADVANCED.md, lib/marked.js, test/new/gfm_code.html, test/new/gfm_code_hr_list.html, test/specs/commonmark/commonmark-spec.js
This is a very simple fix to follow the CommonMark spec for code blocks:
https://spec.commonmark.org/0.27/ Example: https://spec.commonmark.org/0.27/#example-109
Right now Marked defaults to `lang-` for fenced code blocks, which as far I understand it, is legacy from Highlight.js. By enforcing the CommonMark standard developers will be able to leverage other CommonMark tools when using output from Marked.
=> CommonMark code block class names

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Feature_request.md, .github/ISSUE_TEMPLATE/Proposal.md
This adds templates so users are prompted when they create a new issue.
=> Update issue templates

lib/marked.js
Problem:
`replace(/X+$/, '')` is vulnerable to REDOS
Solution:
Replace these instances with a custom rtrim.
=> security: use rtrim, not unsafe /X+$/

lib/marked.js, test/specs/marked/marked-spec.js, test/specs/marked/marked.json
- Fixes empty table cells and multiple slashes before `|`
fixes #1290
=> Fix table cells

docs/AUTHORS.md
This changes `AUTHORS.md` file so that contributor profile images are visible and also changes the order listed from most privileged to least privileged. Also the table format is a little different so that there are no columns.
This follows the format of other large open source projects such as:
- [Webpack](https://github.com/webpack/webpack/blob/master/README.md#core-team) Core Team
- [Ava](https://github.com/avajs/ava/blob/master/readme.md#team) Team
- [XO](https://github.com/xojs/xo/blob/master/readme.md#team) Team
=> Add pictures to AUTHORS.md

lib/marked.js, test/specs/marked/marked-spec.js, test/specs/marked/marked.json
**Marked version:** 0.4.0
**Markdown flavor:** Markdown.pl
Link with names that clashed with properties inherited from the
Object prototype (such as "constructor") were not expanding. This fixes
this issue.
Before this change, markdown of this form...:
Link: [constructor][].
[constructor]: https://example.org/
...resulted in HTML output of this form:
<p>Link: [constructor][].</p>
With this change, it now renders as expected:
<p>Link: <a href="https://example.org/">constructor</a>.</p>
=> fix issues link references and prototypes

README.md
This changes the "install size" badge so it's always pointing to the latest version of marked.
=> Change badge to latest version of marked

lib/marked.js, test/specs/marked/marked-spec.js, test/specs/marked/marked.json
0.4.0
**Markdown flavor:**
GitHub Flavored Markdown
Add a test and fix that trailing punctuation is omitted in link URLs for
markdown like this:
```markdown
(See https://www.example.com/fhqwhgads.)
```
The trailing period and closing parenthesis should not be part of the
link URL.
```html
<p>(See <a href="https://www.example.com/fhqwhgads">https://www.example.com/fhqwhgads</a>.)</p>
```
```html
<p>(See <a href="https://www.example.com/fhqwhgads.">https://www.example.com/fhqwhgads.</a>)</p>
```
Note that the trailing period is included as part of the URL. That's the bug.
=> fix gfm extended autolinking requiring multiple backpedals

README.md, docs/README.md, docs/demo/demo.css, docs/demo/demo.js, docs/demo/index.html, docs/demo/preview.html
- Use an iframe to prevent xss on demo page
- Adds a warning to the readme and docs for displaying unsanitized output HTML
- Fixes #1294
=> use iframe to sandbox generated html

.travis.yml
By default Travis CI clones the last 50 commits. Cloning less means faster checkout and clone times which results in slightly faster builds.
See [the docs](https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth) for more information.
=> Change travis clone depth to 3

docs/USING_ADVANCED.md
- `???` is useless. They should be documented as well as other options.
=> Add undocumented option descriptions

README.md
Sometimes, shields is overloaded and the images don't load.
This switches the badges to render with badgen so that the badges will be more reliable.
There is no visible change here, just speed/reliability.
=> Change badges from shields.io to badgen.net

lib/marked.js, test/new/smartypants_code.html, test/new/smartypants_code.md
`0.5.0` (latest)
**Markdown flavor:** all
- Fixes #1334 
=> Fix typographic substitution in (pre|code|kbd|script) blocks when smartypants=true

lib/marked.js, test/specs/marked/marked-spec.js, test/specs/marked/marked.json
**Markdown flavor:** GitHub Flavored
Fixes #1218 (see [comment](https://github.com/markedjs/marked/issues/1218#issuecomment-422518372))
Fixes #1307
Fixes #1327
I believe this complies better with the gfm spec.
=> Fix auto-linking email

package-lock.json, package.json, test/specs/commonmark/commonmark-spec.js, test/specs/gfm/gfm-spec.js, test/specs/marked/marked-spec.js
**Marked version:** v0.5.0
Update dependencies to use `@markedjs/html-differ` instead of `html-differ`
- Fixes #1330 
=> use @markedjs/html-differ

README.md
This PR adds a couple badges to show out of date dependencies (none) and dev dependencies.
I also updated the gzip size badge to use badgen.net for consistency.
Fixes #1330
=> Add dependency badges to readme

docs/demo/demo.css, docs/demo/demo.js, docs/demo/index.html
Create a details toggle that hides a textarea into which a user can type a JSON-formatted options object.
(For some reason, I can't seem to get the textarea inside a details tag to match the width of the other textareas. After staring at the CSS and banging my head against it, I figured I'd let other people look at it, decide if it was important, and if it was, how to fix it.)
=> Add the ability to specify options on the demo page as JSON

docs/demo/demo.css, docs/demo/demo.js
Commit: da9d155a1e54f058e876e4cd28c04ec4ab296303
**Markdown flavor:** all
When the "options" object provided by users doesn't parse, make the input field red to let them know:
And when it does parse, return to a regular old textarea.
Some kind of visual indication that the options entered into the text box aren't valid.
No such indication.
https://marked.js.org/demo/?text=%23%23%23%20These%20options%20don%27t%20work.&options=a
=> Demo Page: Give user feedback when "options" is not valid JSON.

.travis.yml
Fixes our failing builds.
Node v0.10 went End-of-Life two years ago which is why jasmine (our test framework) won't work anymore (looks like they dropped support awhile ago and just introduced breaking changes recently.
Related: https://github.com/jasmine/jasmine-npm/pull/144
=> Fix builds: remove node v0.10 from travis matrix

package-lock.json, package.json
=> Release v0.5.2

docs/USING_ADVANCED.md
Fix the description for the "breaks" option
**Markdown flavor:** Docs
- Fixes https://github.com/markedjs/marked/issues/1380#issuecomment-442246561
=> fix `breaks` option description

docs/USING_ADVANCED.md
**Markdown flavor:** docs
- Fixes docs to include the version of marked that an option was available
=> Update docs to include "Since" version

lib/marked.js, test/specs/marked/marked.json
**Marked version:** v0.5.2 (revision ed64407e3ddac290658ba042a691b11c40ba5f55)
- Fixes bold + autolink bug with input `__test@test.com__`
This PR fixes a bug of parsing order which can lead autolink to take over parsing of other elements (e.g. bolding). Please look **carefully** before merging this PR: I obviously ran tests and added a new one, but this is probably a **breaking change**. ~~Also, my test should probably not be there, so please feel free to edit (I allowed edit from maintainers)~~ (this has been fixed, c.f. my force push).
`<p><strong><a href="mailto:test@test.com">test@test.com</a></strong></p>`
`<p><a href="mailto:__test@test.co">__test@test.co</a>m__</p>`
Reordering of parsing (autolink processing now just before text).
=> Fix bold around autolink email address

lib/marked.js, test/specs/marked/marked.json
Make urls case insensitive
implements https://github.com/markedjs/marked/pull/1350#issuecomment-427164249
```js
marked("hTtP://fOo.CoM");
// <p><a href=\"hTtP://fOo.CoM\">hTtP://fOo.CoM</a></p>
```
- closes #1350
=> Make autolinks case insensitive

test/new/gfm_del.html, test/new/gfm_del.md
Bookkeeping clean-up for Issue #1230 - remove old test that is now covered by by GFM and CommonMark
=> remove old test covered by gfm/cm

lib/marked.js
It seems to me that such a message will be appropriate. If I did not write very English, the wishes for corrections are accepted.
=> Add message: token type cannot be found

lib/marked.js, test/specs/commonmark/commonmark-spec.js
**Markdown flavor:** CommonMark
- Related to #1216 
```html
<p>1234567890. not ok</p>
```
```html
<ol start="1234567890">
<li>not ok</li>
</ol>
```
Limited ordered list marker length
=> Limit ordered list marker length

bin/marked
**Marked version:** master branch
Hide the JS stack trace on CLI errors 
- Fixes #205 
=> Pretty print ENOENT errors on cli

lib/marked.js, test/specs/commonmark/commonmark-spec.js
**Marked version:** master branch
**Markdown flavor:** CommonMark
- Related to #1216 
```markdown
> foo
- bar
```
```html
<blockquote>
<p>foo
- bar</p>
</blockquote>
```
```html
<blockquote>
<p>foo</p>
<pre><code>- bar</code></pre></blockquote>
```
Fix blockquote paragraph continuation by limiting whitespaces before list item
=> Fix blockquote paragraph continuation

lib/marked.js, test/new/cm_blockquotes.html, test/new/cm_blockquotes.md, test/new/toplevel_paragraphs.html, test/new/toplevel_paragraphs.md, test/original/markdown_documentation_basics.html, test/unit/marked-spec.js
**Marked version:** 0.5.2
**Markdown flavor:** All
This fixes several bugs involving `headerIds: true`.
- Fixes #857
- Fixes #1280 
- Fixes #1354
- Fixes #1374
This adds a new export `marked.Slugger`.
I added several more tests to cover duplicates as well as ampersands.
=> Fix duplicate heading id

docs/AUTHORS.md
Add defibrillator badge for @mccraveiro to the [AUTHORS](https://marked.js.org/#/AUTHORS.md) page.
<table>
<tr>
<td align="center" valign="top">
<a href="https://github.com/mccraveiro">
</a>
<br>
<a href="https://github.com/mccraveiro">Mateus Craveiro</a>
<div>Contributor</div>
<small>Defibrillator</small>
</td>
</tr>
</tbody>
</table>
- related to #1391 
=> Add defibrillator badge for mccraveiro

docs/USING_PRO.md
- Fixes #1416 update document about extending renderer to be equal behavior between code and docs
=> Update documentation about extending Renderer

docs/demo/demo.css, docs/demo/demo.js, docs/demo/index.html, docs/demo/initial.md, docs/demo/worker.js
I added a [web worker](https://developer.mozilla.org/en-US/docs/Web/API/Worker) to the demo page. This will allow easier testing for redos attacks.
You can test it out at: https://docs-8bxhez41v.now.sh/demo/
This PR adds is branched off #1415 with https://github.com/remyhunt/marked/pull/1 merged so we should get that PR merged first.
=> demo worker

README.md, docs/README.md
"As of npm 5.0.0, installed modules are added as a dependency by default, so the --save option is no longer needed. The other save options still exist and are listed in the documentation for npm install."
https://stackoverflow.com/a/19578808/142358
- [x ] no tests required for this PR.
=> Remove --save option as it isn't required anymore

package-lock.json, package.json
- Fix parenthesis url redos #1414
- Update demo site to use a worker #1418 
- Update devDependencies to last stable #1409
- Update documentation about extending Renderer #1417
=> Release 0.6.1

lib/marked.js, test/specs/marked/marked.json
**Markdown flavor:** CommonMark
fixes text in parenthesis after link being added as title.
[marked demo](https://marked.js.org/demo/?text=%5BOne%5D(https%3A%2F%2Fexample.com%2F1)%09(%5BTwo%5D(https%3A%2F%2Fexample.com%2F2))%20%5BThree%5D(https%3A%2F%2Fexample.com%2F3)&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22t …
=> Links parens

lib/marked.js, test/new/list_table.html, test/new/list_table.md
Fix tables in a list
[demo](https://marked.js.org/demo/?text=*%20Fixes%20indented%20tables%20like%20this%3A%0A%0A%20%20%7C%20column1%20%7C%20column2%20%7C%0A%20%20%7C---------%7C---------%7C%0A%20%20%7C%20value1%20%20%7C%20value2%20%20%7C%0A%20%20%7C%20value3%20%20%7C%20value4%20%20%7C&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists …
=> Fix tables in a list

jasmine.json, test/helpers/helpers.js, test/helpers/html-differ.js, test/index.js, test/new/uppercase_hex.html
Update all tests to use html-differ and use syntax for node 4
=> Update tests to node 4 syntax

lib/marked.js, test/redos/quadratic_br.js, test/redos/quadratic_email.js, test/specs/gfm/gfm.0.28.json, test/specs/redos-spec.js
The old regex may take quadratic time to scan for potential email addresses starting at every point.  Fix it to avoid scanning from points that would have been in the middle of a previous scan.
0.1.3 and later (problem introduced by commit 00f1f7a)
- Fixes DoS issue reported privately.
=> Improve worst-case performance of inline.text regex

docs/demo/demo.js
use `@master` in demo for master version
https://docs-ikjy0vxvf.now.sh/demo/
- fixes comment https://github.com/markedjs/marked/issues/1456#issuecomment-478090870
=> use latest commit for demo master

lib/marked.js, test/redos/nested_blockquote.js, test/specs/redos-spec.js
**Markdown flavor:** All
Removes recursion for nested blockquotes
Fixes #1462 [demo](https://marked.js.org/demo/?outputType=html&text=%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E%3E …
=> Nested blockquotes

docs/USING_ADVANCED.md, docs/index.html
Add examples of how to run marked in a worker on node and in a browser.
https://docs-4nj255ohp.now.sh/#/USING_ADVANCED.md#workers
fixes #1184 
=> add docs for workers

docs/README.md
- Updates the docs to show 0.29 as the commonmark and gfm version
=> Update supported spec versions

lib/marked.js, test/specs/redos/nested_blockquote.js
Revert #1464 
Fixes #1494 
#1464 fixes recursion limit for fully nested blockquotes
```
>> a
>> b
```
but it doesn't solve recursion for partially nested blockquotes
```
> a
>> b
```
I'm not sure that we should have a special case for fully nested blockquotes.
=> revert #1464

docs/CONTRIBUTING.md
Update test descriptions in `/docs/CONTRIBUTING.md`
=> update test descriptions in CONTRIBUTING.md

lib/marked.js, test/specs/new/links_paren.html, test/specs/new/links_paren.md
Fix multiple inline links with parenthesis around them
```markdown
([one](http://example.com/1)) ([two](http://example.com/2))
```
([one](http://example.com/1)) ([two](http://example.com/2))
([one](http://example.com/1) ([two](http://example.com/2))
- Fixes https://github.com/markedjs/marked/issues/1459#issuecomment-507046542
=> Link parenthesis

docs/USING_PRO.md
Update doc examples to use es6 syntax.
=> update examples with es6+

now.json
Adds [ZEIT Now](https://zeit.co/now) deployments for `/docs` to https://markedjs.now.sh
=> Add ZEIT Now deployments to docs

lib/marked.js, test/specs/new/list_loose_tasks.html, test/specs/new/list_loose_tasks.md
Render the checkbox inside the `<p>` tag for a loose task list
- Fixes #1534 
=> Loose task list

docs/USING_ADVANCED.md
**Marked version:** docs
Remove warning about node worker threads since they are stable in v12.11.0
=> Node worker threads are stable

docs/USING_ADVANCED.md
**Marked version:** 0.7.0
Documentation link was not pointing to the correct location, because link can't be relative, hardcoding the official documentation website.
Documentation works seamlessly. 
N/A
N/A
=> Typo: Fix link to USING_PRO.md

lib/marked.js, test/specs/new/image_paren.html, test/specs/new/image_paren.md
**Marked version:** 0.7.0
Fix image surrounded by parentheses
fixes #1556
[demo](https://marked.js.org/demo/?outputType=html&text=!%5B%5D(img1.svg)%20(or%20!%5B%5D(img2.svg))&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.7.0) works in v0.6.3 but not v0.7.0
In most cases, this should be a different person …
=> fix image parentheses

docs/USING_ADVANCED.md
- Fixes typo in USING_ADVANCED.md
=> Fix typo in USING_ADVANCED.md

src/defaults.js, test/unit/marked-spec.js
fix regression in `setOptions` being global
=> fix changing global defaults

package.json
This is a common misconception - but browser field is not for pointing to a fully browser-compatible file (like in your case you have wanted to point with it to the UMD bundle). It exists to alias files depending on node-specific modules/APIs to files that can be used in browsers (so for example with node-specific modules/APIs stubbed) after bundling etc. 
For example webpack picks "browser" field over "module" by default if provided and that kinda makes "module" file not-used - but the intention is to actually use it.
As you don't depend on any node-specific stuff the appropriate course of action is to just remove this field from your package.json
=> Remove incorrectly used browser field

src/helpers.js, src/rules.js
Static properties used like this at the top-level are a common tree-shaking / dead code elimination deopt (because they affect other top-level statements) so ideally, this pattern should be avoided as much as possible.
This is the last PR from me today - I'd like to see how those play out first, but I have more changes planned.
=> Remove static properties from helpers

.travis.yml
I think this will fix the wrong user showing up as the committer for the build step on travis ci.
`<>` is used to indicate no email address according to [stackoverflow](https://stackoverflow.com/a/28933328/806777).
=> fix build user

src/rules.js, test/specs/commonmark/commonmark.0.29.json, test/specs/gfm/commonmark.0.29.json, test/specs/new/fences_breaking_paragraphs.html, test/specs/new/fences_breaking_paragraphs.md
**Marked version:** 8.0
**Markdown flavor:** CommonMark & GitHub Flavored Markdown
- Fixes GFM ([Example 116](https://github.github.com/gfm/#example-116)). Only code fences made from backticks [cannot have other backticks in the same line](https://github.github.com/gfm/#example-115). Fences with tildes [can have both tildes and backticks.](https://github.github.com/gfm/#example-116). This change allows the tilde case to work correctly.
Also adds tests for detection of these fences if they should or not break paragraphs.
Implementing code as discussed in https://github.com/markedjs/marked/pull/1598#discussion_r377252499
=> Fix GFM Example 116

docs/USING_ADVANCED.md
**Marked version:** 0.8.0
The `marked` docs show this usage for invoking `highlight.js` to perform syntax highlighting of code blocks:
```js
marked.setOptions({
renderer: new marked.Renderer(),
highlight: function(code) {
return require('highlight.js').highlightAuto(code).value;
},
pedantic: false,
gfm: true,
breaks: false,
sanitize: false,
smartLists: true,
smartypants: false,
xhtml: false
});
```
The markdown code blocks to be highlighted might look like these examples:
````markdown
```sql
SELECT * FROM MY_TABLE;
```
```
This is plain text.
```
````
The documented usage has several serious flaws:
1. The code language (e.g. `sql`) is completely ignored; it is not passed to `highlight.js`
2. The `highlightAuto()` API causes `highlight.js` [to perform the entire …
=> Improve example for invoking highlight.js

src/rules.js, test/specs/new/code_following_table.html, test/specs/new/code_following_table.md, test/specs/new/fences_following_table.html, test/specs/new/fences_following_table.md, test/specs/new/heading_following_table.html, test/specs/new/heading_following_table.md, test/specs/new/hr_following_tables.html, test/specs/new/hr_following_tables.md, test/specs/new/html_following_table.html, test/specs/new/html_following_table.md, test/specs/new/inlinecode_following_tables.html, test/specs/new/inlinecode_following_tables.md, test/specs/new/lheading_following_table.html, test/specs/new/lheading_following_table.md, test/specs/new/list_following_table.html, test/specs/new/list_following_table.md, test/specs/new/strong_following_tables.html, test/specs/new/strong_following_tables.md, test/specs/new/text_following_tables.html, test/specs/new/text_following_tables.md
**Marked version:** 8.0
- Fixes #1467 
Edited rules.js to break GFM tables properly using similar syntax used to break paragraphs.
=> Fix GFM tables not breaking on block-level structures

package-lock.json, package.json
- Fix `marked --help` #1588
- Fix GFM Example 116 code fences #1600
- Send inline html to renderer #1602 (fixes #1601)
- Improve docs example for invoking highlight.js #1603
- Fix block-level elements breaking tables #1598 (fixes #1467)
- break nptables on block-level structures #1617
----
=> Release 0.8.1

docs/USING_ADVANCED.md
GitHub does not, in fact, appear to break on a single line.
=> [docs] Update comment about GitHub breaks

src/Slugger.js, src/TextRenderer.js, test/specs/new/headings_id.html, test/specs/new/headings_id.md
**Marked version:** 0.8.1
- Add html to TextRenderer for html in headings.
- Fix Slugger to remove html tags.
Fixes #1621
=> Render html in heading

src/Parser.js
- Treat escape token as text token for the purpose of creating custom Renderer
Marked should alow treating escaped characters the same way it allows treating unescaped characters for the cases where we need to perform plain text transformation in the Render implementation.
Escaped characters, like `\#` are passed to result raw, but unescaped characters are passed to Render.text() as normal.
=> Treat escape token same way we treat plain text tokens

docs/USING_PRO.md, docs/index.html, src/marked.js, test/unit/marked-spec.js
Add function `marked.use` which takes an options object and merges it into marked options.
The `renderer` and `tokenizer` can be an object with functions that will be merged into the `renderer` and `tokenizer` respectively.
The `renderer` and `tokenizer` functions can return `false` to fallback to the previous function.
```js
const extension = {
breaks: true,
renderer: {
html(html) {
if (html.startsWith('<div')) {
return html.replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
return false;
}
}
};
marked.use(extension);
const html = marked(`
<div>
html renderer will use extension
</div>
<span>will fallback to regular html renderer</span>
options from extension
will be used.
`);
console.log(html);
/* will log:
&lt;div&gt;
html renderer will use extension
&lt;/div&gt; …
```
=> marked.use

docs/USING_ADVANCED.md
Add tokenizer options to the options docs
=> add tokenizer to option docs

docs/USING_PRO.md, src/Lexer.js, src/Tokenizer.js, test/specs/new/codespan_newline.html, test/specs/new/codespan_newline.md, test/unit/Lexer-spec.js
**Marked version:** v1.0.0
- Code spans with a newline should turn the newline into a space according to the [commonmark spec](https://spec.commonmark.org/0.29/#example-335).
- Code spans only remove one space from each end if the text begins and ends with white-space
- fixes any list items with more than one line of text.
- Fixes #1651
- Fixes #1655
=> Codespan newline

src/rules.js, test/specs/new/emphasis_extra tests.html, test/specs/new/emphasis_extra tests.md
**Marked version:** 1.0.0
Fix regression when comma is after underscore emphasis
[CommonMark Demo](https://spec.commonmark.org/dingus/?text=_test_%2C)
[Marked Demo, version 1.0.0 doesn’t work](https://marked.js.org/demo/?text=_test_%2C&options=&version=1.0.0)
[Marked Demo, version 0.8.2 works](https://marked.js.org/demo/?text=_test_%2C&options=&version=0.8.2)
Fixes #1659 
=> fix underscore emphasis then comma

package.json
**Marked version:** 1.0.0
Add `browser` field to `package.json` that points to `lib/marked.js` so webpack will use es5 version to bundle for browsers.
- Fixes #1630
=> add browser field to point to es5

src/Renderer.js, test/specs/new/code_compensation_indent.html, test/specs/new/code_consistent_newline.html, test/specs/new/code_consistent_newline.md
1.0.0
Code blocks with and without language are both rendered with the trailing new line.
Code block with language has trailing newline, but code block without language does not.
?
=> render code with and without language with the trailing newline

docs/USING_ADVANCED.md, docs/USING_PRO.md, docs/index.html, src/Tokenizer.js, src/defaults.js, src/marked.js, test/unit/Lexer-spec.js, test/unit/marked-spec.js
**Marked version:** 1.0.0
Using an async highlighting function was broken in v1.0.0 when we moved block tokens in blockquote and lists from the top level of the tokens array to a `tokens` property on the blockquote or listitem token.
This PR adds a public method to easily iterate over all tokens and send each token to a function specified by the user (`marked.walkTokens(tokens, callback)`) and uses that function to highlight code blocks asynchronously.
This also adds a `walkTokens` option so extensions can use it to run a function for each token.
**Example:** Overriding heading tokens to start at h2.
```js
const marked = require('marked');
// Override function
const walkTokens = (token) => {
if (token.type === 'heading') {
token.depth += 1;
}
};
marked.use({ walkTokens });
// Run marked …
```
=> add walkTokens and fix highlight async

src/Tokenizer.js, src/rules.js, test/specs/new/image_links.html, test/specs/new/image_links.md
**Marked version:** 1.1.0
Fix image link with `\[` or `\]` in alt text
[demo](https://marked.js.org/demo/?text=%23%20Expected%20result%0A%0A%5B!%5BManny%20Pacquiao%5D(https%3A%2F%2Fimg.youtube.com%2Fvi%2Fs6bCmZmy9aQ%2F0.jpg%20%22manny%22)%5D(https%3A%2F%2Fyoutu.be%2Fs6bCmZmy9aQ)%0A%0A%23%20Actual%20result%0A%0A%5B!%5B%5C%5BManny%20Pacquiao%5C%5D%5D(https%3A%2F%2Fimg.youtube.com%2Fvi%2Fs6bCmZmy9aQ%2F0.jpg%20%22manny%22)%5D(https%3A%2F%2Fyoutu.be%2Fs6bCmZmy9aQ)%0A%0A%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20true%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20% …
=> fix image links with escaped brackets

src/marked.js, test/unit/marked-spec.js
**Marked version:** 1.1.0
Fix bug when using synchronous highlighter asynchronously
- Fixes #1684 
=> fix async highlight not async

docs/README.md
fixes 
**Marked version:** 1.1.0 and prior (commit b198b55 and prior)
**Markdown flavor:** CommonMark and GitHub Flavored Markdown
- Fixes #1718
=> clarify level of support for Markdown flavors

docs/CONTRIBUTING.md, package.json, test/rules.js
This is just a developer tool to show the fully compiled rules from `src/rules.js` by running `npm run rules`
You can also specify paths to get just certain rules:
=> Add `npm run rules`

docs/USING_PRO.md, src/Slugger.js, test/unit/marked-spec.js
**Marked version: 1.1.0**
**Markdown flavor: n/a**
This PR adds a feature that allows the developer to use the default slugger without updating the internal accumulator. I have seen a use case for this when developers are implementing their own custom renderers. For example, see [this function](https://github.com/tc39/proposal-temporal/blob/5838233ecf733f70361880f237ed8c3fa8d5b837/docs/buildDocs.js#L45-L64) in the TC39 temporal-proposal repository. The changes made can be summarized as:
- Extends the default slugger with the ability to generate slug text without trigger internal communication.
- Separates slugger responsibilities into methods for re-use.
=> NFE: add dry run capabilities to default slugger

SECURITY.md
**@mention the contributor:**
I would like to recommend that @styfle be promoted to an owner on the MarkedJS GitHub organization.
When we started this journey almost three years ago my desire(s) was (were) pretty simple. I actually can't believe it's taken this long for me to realize Steve wasn't already an owner.
Over the years he has stepped up to create a very robust documentation site, which we didn't have before. The site has done wonders to make issue creation and support easier for our users. The latest being #1742 being the latest in a long, long list.
My part in this has always been to primarily to watch out for the community, chip in where I can on code and reviews, and that sort of thing. @styfle and @UziTech have done a lot of heavy lifting making that job easier and have been …
=> Org. owner to Styfle

docs/INDEX.md, docs/USING_ADVANCED.md, docs/_document.html, src/Lexer.js, src/Parser.js, src/marked.js, test/unit/marked-spec.js
**Marked version:** v1.1.1
Create a method (`marked.parseInline()`) that will parse only inline markdown. This is useful for parsing fragments of markdown that should only contain inline elements.
Example:
```js
const marked = require('marked');
const blockHtml = marked('**strong** _em_');
console.log(blockHtml); // '<p><strong>strong</strong> <em>em</em></p>'
const inlineHtml = marked.parseInline('**strong** _em_');
console.log(inlineHtml); // '<strong>strong</strong> <em>em</em>'
```
- Fixes #1760
- Fixes #395
=> Parse inline

src/Tokenizer.js, test/specs/commonmark/commonmark.0.29.json, test/specs/gfm/commonmark.0.29.json
**Marked version:** 1.1.1
fixes indented code in list item. Passes 100% tabs spec.
=> fix: fix indented code in list item

src/Lexer.js, src/helpers.js
**Marked version:** 1.2.0
`string.repeat` is not a function in IE11. If we are still supporting IE11 then we need to create our own repeat helper function. I searched for the fastest function and found https://stackoverflow.com/a/5450113/806777.
I'm not exactly sure how we can write a test to make sure `string.repeat` isn't used in the future since even node v4 supports `string.repeat`.
- Fixes #1771 
=> fix: remove string.repeat for ie11

package-lock.json, package.json, test/bench.js
**Marked version:** 1.2.2
Remove `markdown` devdependency from benchmarks since it is unmaintained and has a security vulnerability.
This doesn't affect marked, just the benchmark tests.
=> chore(deps): Remove markdown dependency

docs/_document.html, docs/demo/demo.js
Fix [codeql](https://github.com/markedjs/marked/security/code-scanning) issues in docs
=> chore(docs): Codeql fixes

LICENSE.md, README.md, docs/AUTHORS.md, docs/PUBLISHING.md, docs/_document.html
- Add @calculuschild to Authors table.
- Add link to Versioning docs in sidebar.
- Update Versioning to be more specific on what counts as a breaking change.
- Remove Deps badges since https://david-dm.org is down. (fixes #1833)
- Add MarkedJS copyright to license.
=> chore(docs): update versioning and other docs

.eslintrc.json, docs/.eslintrc.json, package-lock.json, package.json, test/.eslintrc.json
[eslint-plugin-standard](https://github.com/standard/eslint-plugin-standard#deprecated-this-package-isnt-used-by-standard-anymore-as-of-standard-v16-see-httpsgithubcomstandardstandardissues1316) is deprecated
=> chore(dev-deps): remove eslint-plugin-standard

src/Tokenizer.js, src/rules.js, test/specs/commonmark/commonmark.0.29.json, test/specs/gfm/commonmark.0.29.json, test/specs/new/link_lt.html, test/specs/new/link_lt.md
**Marked version:** v1.2.5
Fixes CommonMark tests [486](https://spec.commonmark.org/0.29/#example-486), [489](https://spec.commonmark.org/0.29/#example-489), [490](https://spec.commonmark.org/0.29/#example-490), [491](https://spec.commonmark.org/0.29/#example-491)
- Fixes #1639
=> fix: fix link with angle brackets around href

src/Lexer.js, src/Renderer.js, src/Tokenizer.js, src/rules.js, test/specs/new/code_compensation_indent.html, test/specs/new/code_consistent_newline.html, test/specs/new/whiltespace_lines.html, test/specs/new/whiltespace_lines.md, test/unit/marked-spec.js
**Marked version:** v1.2.7
The whitespace is removed from lines with only whitespace. This causes problems in code blocks where the whitespace matters.
This PR keeps the spaces in blank lines and adds them to output.
This PR also adds a new line character to the end of all code blocks.
- Fixes #1884 
=> fix: leave whitespace only lines alone

src/Tokenizer.js, test/specs/new/list_align_pedantic.html, test/specs/new/list_align_pedantic.md
**Marked version:** v1.2.8
**Markdown flavor:** Markdown.pl
Sublists with single space are rendered as sublists in pedantic.
- Fixes #1923
=> fix: allow sublist to be single space in pedantic

docs/USING_PRO.md, lib/marked.esm.js, lib/marked.js, package-lock.json, package.json, src/Lexer.js, src/Tokenizer.js
**Marked version:** 1.2.9
- Fixes #1906. Joins together adjacent inline `text` tokens similar to how block text tokens are merged. HTML output doesn't change, but this makes it easier to make a custom renderer since text tokens aren't broken up.
=> fix: Join adjacent inlineText tokens

docs/USING_PRO.md
The docs don't mention how the latex example won't actually work with inline latex, ie. `foo $bar$ baz`.
Not a fix, Just wanted to clarify docs to save debugging time until #1948 is fixed.
=> docs: warn about broken inline latex example

docs/demo/demo.js, docs/demo/worker.js
**Marked version:** docs
Fix default options not loaded before initial markdown parsed in demo.
- Fixes #1982
=> docs: fix demo initial options not loaded

lib/marked.js
Related to https://github.com/markedjs/marked/issues/2000
2.0.1
**Markdown flavor:** all
- Fixes https://github.com/markedjs/marked/issues/2000
Markdown nodes all have a `type` property to ease working with the markdown tree.
`def` nodes do not have a `type` property. 
Using `walkTokens` in typescript, I have the need to discriminate between nodes; the https://www.npmjs.com/package/@types/marked package doesn't define a `type` member for the `Def` interface, seemingly because there is not one here either.
=> Add a `type` property to the `def` tokenizer's return object

src/Tokenizer.js
Hmm I think I modified the wrong file (`lib/marked.js`) in the previous PR (see https://github.com/markedjs/marked/pull/2001) , this should be the right one ! Sorry for that.
2.0.2
- Fixes https://github.com/markedjs/marked/issues/2000
Markdown nodes all have a `type` property to ease working with the markdown tree.
`def` nodes do not have a `type` property. 
Using `walkTokens` in typescript, I have the need to discriminate between nodes; the https://www.npmjs.com/package/@types/marked package doesn't define a `type` member for the `Def` interface, seemingly because there is not one here either.
=> Add a `type` property to the `def` tokenizer's return object  - again

build-docs.js, docs/USING_ADVANCED.md
Fixes deprecated usage of highlight.js in the docs, see https://github.com/highlightjs/highlight.js/issues/2277
[Preview Docs →](https://markedjs-git-docs-highlightjs-usage-markedjs.vercel.app/using_advanced)
=> docs: update highlight.js usage

src/marked.js, test/unit/marked-spec.js
`walkTokens` option was is not called when calling marked with a callback function.
=> fix walkTokens not called on async marked call

.github/workflows/tests.yml, package.json, src/Lexer.js, src/Parser.js, src/marked.js, test/unit/marked-spec.js
**Marked version:** 2.1.0
remove optional chaining to fix node v12 support
update engines to support node v12
test on node v12
- Fixes #2106 
=> fix: fix node v12

.github/workflows/tests.yml, package.json
=> fix: add Node.js 10 to CI and loosen `engines` field

package-lock.json, package.json, src/rules.js, test/specs/commonmark/commonmark.0.30.json, test/specs/gfm/commonmark.0.30.json, test/specs/gfm/gfm.0.29.json
**Marked version:** v2.1.1
**Markdown flavor:** CommonMark, GitHub Flavored Markdown
Update CommonMark and GFM specs to [v0.30](https://github.com/commonmark/commonmark-spec/releases/tag/0.30)
- add [`textarea`](https://spec.commonmark.org/0.30/#example-171) to the list of html tags that don't end at the first blank line.
=> fix: update commonmark spec to v0.30

.github/workflows/tests.yml, package.json
Drop support for node 10 in v3
=> drop node 10 support

README.md, docs/PUBLISHING.md
**Marked version:** 2.0.0
Updates docs to describe Node.js support clearly, and clarify the strategy for dropping old versions of Node.js in relation to semver.
More clear docs for consumers
n/a
n/a
=> Update docs to clarify Node.js and browser support

docs/USING_PRO.md
[Extension docs](https://marked.js.org/using_pro#extensions) are indented incorrectly. It looks like `renderer` is a part of the `tokenizer` section.
=> chore(docs): fix extension docs indentation

src/Tokenizer.js, test/specs/new/autolink_after_link.html, test/specs/new/autolink_after_link.md
**Marked version:** 3.0.0
`inLink` state is not reset after creating a link token so GFM auto-urls are not being tokenized as links.
- Fixes #2180 
=> fix: fix gfm urls after link

docs/USING_ADVANCED.md
To properly integrate [highlight.js](https://github.com/highlightjs/highlight.js/) when using `marked.setOptions`, you need to leverage `langPrefix` to add an additional `hljs` class to the top-level `<code>` element which will be rendered.
Closes #2171
=> chore(docs): Use `langPrefix` in `highlight.js` example.

src/rules.js, test/specs/new/space_after_table.html, test/specs/new/space_after_table.md
**Marked version:** 3.0.1
fix blank line with only whitespace after table
- Fixes #2187
=> fix: stop table at lines with only whitespace

package.json
Change `main` to point to `./lib/marked.cjs` instead of `./lib/marked.esm.js` for compatibility with 'other' loaders (eg jest) in a non-ES module environment.
This was tested in an ESM repo both directly (node) and under jest with no problems.
4.0.0
- Fixes #2274 
=> fix: Set commonJS code as `main` in `package.json`

.gitattributes
Some tests fail on windows due to `\r\n` vs `\n`:
code_compensation_indent
code_consistent_newline
whiltespace_lines (sic)
Updated .gitattributes to preserve the `eol` value.
Files in test/specs/new were refreshed to have new attributes applied prior to testing.  No failures were reported.
n/a
- [] no tests required for this PR.
Updated title to clarify this only applies to running the test suite and not general usage.
=> fix: avoid linefeed errors running tests on windows

src/rules.js, test/specs/gfm/gfm.0.29.json, test/specs/new/table_following_text.html, test/specs/new/table_following_text.md, test/unit/Lexer-spec.js
Uses `table` pattern to interrupt `paragraph`. So an empty line won't be required for GFM tables.
Test cases added for this change.
**Marked version:** 4.0.4
- Fixes #1733 
=> Make No Empty Line Required Before GFM Tables

docs/USING_PRO.md
**Marked version:** 4.0.6
- The example in the documentation of [custom extensions](https://marked.js.org/using_pro#extensions) used `marked.use({ extensions: [descriptionList] });` to add the extension provided above while the name of the extension is `descriptionlist`.
=> fix: rename inconsistent variable in example

src/Tokenizer.js, test/specs/new/multiple_sub_lists.html, test/specs/new/multiple_sub_lists.md
4.0.6
Fixes #2314
#2302 mistakenly used `list.loose` as a flag to end list items early if they start with two blank lines. Technically that is a different scenario from being "loose", so legitimate loose lists were also hitting that flag and prematurely ending the list after the second item. This PR just adds a separate flag `endEarly` to handle that case.
=> Fix every third list item broken

src/Lexer.js, src/Tokenizer.js, test/unit/Lexer-spec.js, test/unit/marked-spec.js
4.0.8
This PR stops ignoring single `\n` characters and makes sure they're properly represented in the token list for each token type in the lexer.
- Fixes #2340
=> Fix lexer and tokenizer to retain line breaks properly

src/helpers.js, test/specs/new/nbsp_following_tables.html, test/specs/new/nbsp_following_tables.md
**Marked version:** 4.0.11
Fixes #2371 
With this change I expect the example given in the issue to not cause a JavaScript error.
The test case no longer throws an error and instead renders the table properly.
This PR adds a simple check to the `splitCells` helper function that validates that the `cells` array isn't empty before calling `cells[cells.length - 1].trim()`. This prevents the error "Cannot read properties of undefined (reading 'trim')" from being thrown.
=> Add check in splitCells to prevent calling trim on undefined

src/helpers.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
=> chore: replace deprecated String.prototype.substr()

bin/marked.js, build-docs.js, src/Lexer.js, src/Renderer.js, src/Slugger.js, src/helpers.js, src/marked.js
- Fixes #### (if fixing a known issue; otherwise, describe issue using the following format)
=> added some jsdoc

src/Renderer.js
- Fixes #### (if fixing a known issue; otherwise, describe issue using the following format)
=> use template literal on some few places

src/rules.js
Just a small tweak so `emStrong` regex doesn't have to check character-by-character. Try to consume everything up to the delimiter we are checking for. Should be a small speedup.
In response to #2355 .
Compare
Old: https://regex101.com/r/BonHgn/1
New: https://regex101.com/r/C47yws/1
=> Allow emStrong regex to consume more characters at once

.github/workflows/codeql-analysis.yml, .github/workflows/tests.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
=> Set permissions for GitHub actions

src/Tokenizer.js, test/specs/new/table_reference_link.html, test/specs/new/table_reference_link.md
**Marked version:** 3.0.0 - 4.0.15
Reference links inside tables were broken in v3.0.0
- Fixes #2217 
=> fix: fix ref links inside table

src/Lexer.js, test/unit/marked-spec.js
**Marked version:** v4.0.18
Allow second parameter for `lexer.inline` to be optional. See https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/61664#discussioncomment-3376571
=> fix: make second parameter optional on lexer.inline

docs/USING_ADVANCED.md, docs/USING_PRO.md, docs/_document.html, src/Lexer.js, src/Tokenizer.js, src/defaults.js, src/marked.js, test/bench.js, test/unit/marked-spec.js
The `walkTokens` function returns the values of the function so someone can await any Promises.
The way I see this working is anyone who wants to do anything async will do it by awaiting `marked.walkTokens(tokens, callback)`
Something like:
```js
const tokens = marked.lexer(markdown)
await Promise.all(marked.walkTokens(tokens, asynFunction))
const html = marked.parser(tokens)
```
To make the walkTokens option be able to be async we have to introduce an `async` option so users can instead write:
```js
const walkTokens = asyncFunction
marked.use({walkTokens, async: true})
const html = await marked.parse(markdown)
```
or in an extension:
```js
const importUrl = {
extensions: [{
name: 'importUrl',
level: 'block',
start(src) { return src.indexOf('\n:'); },
tokenizer(src) {
const rule = …
```
=> Async marked

docs/USING_ADVANCED.md, docs/USING_PRO.md, lib/marked.cjs, lib/marked.esm.js, lib/marked.umd.js, src/defaults.js, test/bench.js
=> Removing smartLists from docs and code

docs/INDEX.md, docs/_document.html
Adds new section for Tools using Marked
- Fixes #2337
- Links #2601 
Adding Tools table in docs,
- These tools are single-page creation tools using Marked.
Added this.
=> Adding Tools using Marked in docs

docs/INDEX.md
- Fixes #2139
Added clarification about ZERO WIDTH unicode characters interfering with parsing. 
=> docs: Add note about zero width unicode characters (#2139)

package.json
This allows tools like marked-man to extend marked and still use its cli.
=> feat: export bin/marked

api/dingus.js
Update dingus to es module.
https://marked.js.org/api/dingus?text=Hello%20World fails with error:
```
ERROR	ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/var/task/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```
test at https://marked-website-git-fork-uzitech-api-markedjs.vercel.app/api/dingus?text=Hello%20World
=> chore: update dingus

docs/USING_ADVANCED.md, docs/_document.html
Add documentation for #2629 
[preview](https://marked-website-git-fork-uzitech-cli-extension-docs-markedjs.vercel.app/using_advanced#cli-extensions)
=> docs: add cli extension docs

src/Lexer.js, src/Tokenizer.js, src/rules.js, test/specs/new/escape_within_emphasis.html, test/specs/new/escape_within_emphasis.md, test/unit/Lexer-spec.js
...particularly right at the end.
Fixes #2280
This resolves the issue at hand, but further improvements will be necessary to bring things fully into alignment with https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis .
=> fix: Support escapes within emphasis

src/Tokenizer.js, test/specs/commonmark/commonmark.0.30.json, test/specs/gfm/commonmark.0.30.json
**Marked version:** 4.1.1
Fixes [backslash escapes](https://spec.commonmark.org/0.30/#backslash-escapes) for common mark specs [`#23`](https://spec.commonmark.org/0.30/#example-23), [`#24`](https://spec.commonmark.org/0.30/#example-24), and [`#202`](https://spec.commonmark.org/0.30/#example-202)
=> fix: fix escape characters in links

src/Renderer.js, src/helpers.js, test/specs/commonmark/commonmark.0.30.json, test/specs/gfm/commonmark.0.30.json
**Marked version:** 4.2.2
Fix `Entity and numeric character references` specs [#28](https://spec.commonmark.org/0.30/#example-28) and [#34](https://spec.commonmark.org/0.30/#example-34).
In order to fix the last 2 `Entity and numeric character references` specs we would need to convert html entities to percent encoded with this json map: https://html.spec.whatwg.org/entities.json. This would increase the size of marked significantly (almost double 48k -> 84k) and provide very little benefit to the actual output.
=> fix: fix entity specs

src/Tokenizer.js, src/rules.js, test/specs/commonmark/commonmark.0.30.json, test/specs/gfm/commonmark.0.30.json
**Marked version:** 4.2.2
Fix `Link reference definitions` spec tests [#195](https://spec.commonmark.org/0.30/#example-195) and [#200](https://spec.commonmark.org/0.30/#example-200)
`Link reference definitions` spec tests will be at 100% :tada:
=> fix: fix link reference definitions specs

src/rules.js, test/specs/commonmark/commonmark.0.30.json, test/specs/gfm/commonmark.0.30.json, test/unit/Lexer-spec.js
**Marked version:** 4.2.2
Allow multiline setext headings. This fixes 3 `Setext headings` spec tests but breaks one test that was only passing because we didn't allow multiline setext headings.
The last setext heading test will actually have to be fixed in the blockquote tokenizer.
There was also one unit test that was wrong so I just deleted it. There are other tests that prevent the same regression.
=> fix: fix multiline setext headings

src/marked.js, test/unit/marked-spec.js
**Marked version:** 4.2.2
- Fixes #2649 
=> fix: fix marked.use with multiple args

src/Tokenizer.js, test/specs/new/list_loose.html, test/specs/new/list_loose.md, test/unit/Lexer-spec.js
**Marked version:** 4.2.3
Currently list items' `loose` property is not set correctly for `loose` lists ([demo](https://marked.js.org/demo/?outputType=lexer&text=-%20item%201%0A-%20item%202%0A%0A-%20item%203&version=4.2.3))
=> fix: loose list items are loose

src/Tokenizer.js, test/unit/Lexer-spec.js
**Marked version:** 4.2.3
blockquote content should be parsed as if it is top level markdown. This currently breaks in lists that are not loose.
- Fixes #2670 
=> fix: use paragraph token in blockquote in list

docs/demo/initial.md
Adds clarity to the location of the dropdown in the [Marked Demo](https://marked.js.org/demo/)
When looking at the demo, "upper right" didn't seem correct when describing the location of the dropdown. It's a  minor change, but hopefully "above" will be more clear.
=> clarify dropdown location

src/Tokenizer.js, test/specs/new/paragraph-after-list-item.html, test/specs/new/paragraph-after-list-item.md
**Marked version:** 4.2.4
- Fixes #2685
=> fix: fix paragraph continuation after block element

.devcontainer/devcontainer.json
Closes #2699 with the basic node 14 devcontainer. Do note that a dev container for 12 doesn't exist, so if this is preferred, I would have to add a Dockerfile as well.
=> chore: add .devcontainer config

docs/USING_PRO.md, src/marked.js, test/unit/marked-spec.js
**Marked version:** 4.2.12
Always return a promise if `async` option is `true`.
- Fixes #2721 
=> fix: always return promise if async

docs/USING_PRO.md, docs/_document.html, src/Hooks.js, src/defaults.js, src/helpers.js, src/marked.js, src/rules.js, test/unit/marked-spec.js
**Marked version:** 4.2.12
This is the start of implementing #1878
Add `preprocess` and `postprocess` hooks so extensions can process the markdown and options before sending it to marked and they can process the html after marked is done with it.
A couple use cases come to mind. We can have a sanitize extension that works on the final output html. We can have an extension that parses front-matter for the options marked should use during the parsing.
**Example:** Set options based on [front-matter](https://www.npmjs.com/package/front-matter)
```js
import { marked } from 'marked';
import fm from 'front-matter';
// Override function
const hooks = {
preprocess(markdown) {
const { attributes, body } = fm(markdown);
for (const prop in attributes) {
if (prop in this.options) {
this.options[prop] …
```
=> feat: add preprocess and postprocess hooks

docs/USING_PRO.md
**Marked version:** latest
- Fixes #2082 
=> chore(docs): update renderer docs

.github/workflows/tests.yml, package.json
> # 🚨  BREAKING CHANGE 🚨 
> do not submit until we are ready to release v5.0.0
Update minimum node version to v18
=> fix: update min node to v18

docs/USING_ADVANCED.md, src/Renderer.js, src/helpers.js, src/marked.js, test/unit/marked-spec.js
> # 🚨  BREAKING CHANGE 🚨 
> do not submit until we are ready to release v5.0.0
Deprecate the following options:
| Option | Replacement|
|---------|---------------|
| `highlight`, `langPrefix`, and `callback`| [marked-highlight](https://www.npmjs.com/package/marked-highlight)|
|`mangle`| [marked-mangle](https://www.npmjs.com/package/marked-mangle)|
|`baseUrl`| [marked-base-url](https://www.npmjs.com/package/marked-base-url)|
|`smartypants`| [marked-smartypants](https://www.npmjs.com/package/marked-smartypants)|
|`xhtml`| [marked-xhtml](https://www.npmjs.com/package/marked-xhtml)|
|`headerIds` and `headerPrefix`| [marked-gfm-heading-id](https://www.npmjs.com/package/marked-gfm-heading-id)|
This will be a breaking change so should be done in the next major version.
This only deprecates the …
=> fix: deprecate options

docs/USING_PRO.md, src/Parser.js, src/Renderer.js, src/Tokenizer.js, test/unit/Lexer-spec.js
Add `block` parameter to html tokens and a `block` param to html renderer to allow different renderings for inline and block level html.
- Fixes #1745 
=> feat: add block param to html renderer

src/helpers.js
**Marked version:** 5.0.0
This removes the warning for langPrefix unless it is changed.
The default warnings can be silenced by setting the following options:
```js
marked.use({
mangle: false,
headerIds: false
});
```
=> fix: only warn if langPrefix is changed

src/helpers.js
**Marked version: 5.0.1**
- Fixes #2797 
Adds a few clarifying words to the deprecation messages for those parameters that are enabled by default. Users are confused about why they are receiving warnings for parameters they didn't manually set; this help indicate that they are enabled by default and they can also just disable the setting if they don't want to get the extension.
I could see changing "historically" to "currently" (or just removing), if that is more clear wording.
=> Clarify deprecation messages for default parameters

src/rules.js, test/helpers/load.js, test/specs/redos/quadratic_em_mask.cjs
**Marked version:** v5.0.2
Fix quadratic execution in em mask regexp
=> fix: fix quadratic execution in em mask

.github/workflows/tests.yml
use `check-latest` to make sure github actions uses latest of specified node versions
=> test: make sure we are testing on latest versions

src/rules.js, test/specs/new/incorrectly_formatted_list_and_hr.html, test/specs/new/incorrectly_formatted_list_and_hr.md
**Marked version:** v4.2.3 and later
**Markdown flavor:** Markdown.pl
- Fixes #2735 
=> fix: fix hr after list

src/Lexer.js, src/Tokenizer.js, src/rules.js, test/specs/new/escape_within_emphasis.html, test/specs/new/escape_within_emphasis.md
**Marked version:** 5.0.4
**Markdown flavor:** GFM
- Simplifies the previous solution from #2627, and also fixes some missing edge cases mentioned therein: [comment](https://github.com/markedjs/marked/pull/2627/files#r1010018940)
Literally the only cause of #2280 failing was because `\` was not included in the punctuation list. I added that, and undid the complex solution from #2627.
Also changed the "mask out escaped EmStrong" code to mask out *all* escaped tokens, which handled the new test case `_\\_` where the backslash is itself escaped. Could have been handled by a more complex escapedEmStrong regex, but this solution I think can apply to a few other locations where escapes come up, in a future cleanup PR, and doesn't appear to add any slowdown compared to the current solution.
In …
=> fix: Fix more Escape conflicts

src/Lexer.js, src/Tokenizer.js, src/rules.js
**Marked version:** 5.0.5
Cleans up the unicode punctuation from #2811 by using `\p{P}` instead of a long list of unicode characters. There are a handful of punctuation characters ``$+<=>`^|~`` not included in that set for whatever reason, so they are still specified here. Includes the accompanying tweaks to a couple other regexes to apply it correctly. This also lets us cover a slightly larger punctuation set since my understanding is JS unicode symbols end at `\uFFFF` but there are a few more after that.
And a tiny unrelated logic simplification in the emStrong Tokenizer.
My only question is if there is a better way to exclude single characters from `\p{P}`, for instance in the emStrong, we don't include the current delimiter `*` or `_` in …
=> fix: Simplify unicode punctuation

docs/INDEX.md
Introducing **the ULTRALIGHT SIMPLISTIC raito rendering utility**, among utilities that use markup.js, as a powered wiki engine, which competes strongly against other engines such as github wiki and mediawiki itself
Including the **raito** into the utilities that uses marked.js project, it has powered features such as:
* **include macro**, can be use to reuse common pages without rewrite same parts into other pages, this is a mayor feautre from wikimedia and redmine wiki engines, still do not supported inside github wiki or gitlab wikis
* **static site generator**, can be used as a fast generation web, just by editing the index.html css style, such can be changed to bootstrap just by minimal tune
=> Introducing the wiki raito rendering engine among utilities

.github/workflows/tests.yml, package.json
**Marked version:** `master`
- Fixes https://github.com/markedjs/marked/pull/2767#issuecomment-1534262376
Node 16 is still supported until September and there's no code in `marked` that doesn't work on Node 16, so it's unnecessarily aggressive to disallow it.
Should be able to run marked on Node 16
`engines` field gets in the way prior to this PR
=> fix: Add support for Node 16

.gitattributes
This PR adds `lib/*` and `marked.min.js` to the  `.gitattributes` file in order to suppress them in diffs.
See https://github.com/github-linguist/linguist/blob/master/docs/overrides.md
=> chore(git): mark `lib/*` as generated in `.gitattributes`

package.json
**Marked version:7.0.1**
There is no necessery to publish`src` folder to npm, and this optimize can reduce `marked` package install size.
=> chore: optimize npm publish package size

src/MarkedOptions.ts, src/Renderer.ts, src/Tokenizer.ts, tsconfig.json
**Marked version:** 7.0.1
Fix sourcemaps and circular dependencies
sourcemap aren't adding sourceContent in release
https://stackoverflow.com/questions/63218218/rollup-is-not-generating-typescript-sourcemap
=> fix: fix sourcemaps and circular dependencies

build-docs.js, docs/AUTHORS.md, docs/CONTRIBUTING.md, docs/USING_ADVANCED.md, docs/_document.html, docs/css/hljs-github.css, docs/css/style.css, docs/demo/demo.css, docs/demo/demo.js, docs/demo/index.html, docs/demo/worker.js, package-lock.json, package.json
Update docs
- Update highlight js css
- Use markedHighlight extension
- Add Instance link
- Fix headers with headerIds: false
- Import esm version in worker
- Remove unfetch and ESPromise dependencies
- Remove non-worker demo parser
- Animate response time when markdown updates
=> docs: update docs

src/Tokenizer.ts, test/specs/new/emoji_inline.html, test/specs/new/emoji_inline.md
- Fixes #2841
- Supersedes #2879
Many emojis are 2+ unicode chars long. The \u tag which allows searching for punctuation also counts emojis as single chars, which throws off character count when slicing strings. Spreading the strings into an array restores the correct character count. There is probably some overhead slowdown but not that I can detect.
Eventually the `\v` regex tag (in Node 20) can replace`\u` to get an accurate char count natively.
=> Fix unicode Regex miscounting emoji length

docs/USING_PRO.md
HEAD
- Fixes #2939 #2945
- [ x ] no tests required for this PR.
=> [DOCS] Tweaks to docs to make them clearer, regarding hooks and options to lexer/parser

src/Instance.ts, test/unit/marked-spec.js
**Marked version:** 6.0.0
When `async: true` is set by an extension we need to make sure `marked.parse` returns a promise to await the extension. If the user passes `async: false` to the `marked.parse` function as a second argument we want to warn them that marked will ignore that option and continue to return a Promise.
- Fixes #2919 
=> fix: ignore async: false when async: true is set by an extension

.github/workflows/tests.yml, src/Instance.ts, src/MarkedOptions.ts, src/marked.ts
**Marked version:** v7.0.4
Remove `unknown` from walkTokens return types
- Fixes https://github.com/markedjs/marked/pull/2893#pullrequestreview-1595805674
=> fix: remove unknown from walkTokens return types

src/Parser.ts, test/unit/marked-spec.js
**Marked version:** 8.0.0
Fixes #2970
Add back space after checkbox in task list.
=> fix: fix space removed after checkbox

src/Tokenizer.ts
**Marked version:** v8.0.0
`String.prototype.trimLeft()` / `trimRight()` is deprecated for ES2019. Changed to use `trimStart() / trimEnd()` instead.
=> fix: deprecated trimLeft/trimRight

docs/USING_PRO.md, test/unit/marked-spec.js
Remove Slugger from docs. Slugger was removed in v8.0.0 when the deprecated options were removed
- Fixes #2983
=> docs: remove slugger

src/Tokenizer.ts, test/specs/new/emoji_inline.html, test/specs/new/emoji_inline.md
**Marked version:** 9.0.1
- Fixes #2988 
=> fix: fix unicode emstrong

docs/USING_PRO.md
- Fixes two typos in `USING_PRO.md`: replacing "render" with "renderer" and `extenstions` with `extensions`.
=> docs: fix typo in `USING_PRO`

bin/main.js, man/marked.1.md
**Marked version:** c9ffa649a4671afec2f18fe11777693b9007ee6a
- Fixes #2012
If the `--no-clobber` / `-n` option is set, it throws an error if the output file already exists.
=> feat: add `--no-clobber` option to CLI

package.json
This change adds the minified js to the package's export conditions.  This will allow projects using PnP to have access to the script during build time.  
Fixes #2885
=> fix: add marked.min.js to package exports

src/Tokenizer.ts, test/unit/Lexer-spec.js
**Marked version:** 9.1.1
Trim newline from blockquote token.text
- Fixes #3036
=> fix: trim newline from blockquote token.text

src/Lexer.ts, test/specs/original/markdown_documentation_basics.html, test/specs/original/markdown_documentation_basics.md, test/specs/original/markdown_documentation_syntax.html, test/specs/original/markdown_documentation_syntax.md, test/unit/marked-spec.js
This PR fix the typo in multiples files
```pseudo
unecessary > unecessary
interchangable > interchangeable
entites > entities
asign > assign
```
=> Chore: Typo fixed in multiple files

docs/USING_ADVANCED.md
Add `marked-alert` to known extensions
=> docs: add `marked-alert` to known extensions

package-lock.json, package.json
Which is compatible with marked@9
Very few changes besides that.
=> chore: Update marked-man@2.0.0

src/Tokenizer.ts, test/specs/new/emoji_inline.html, test/specs/new/emoji_inline.md
**Marked version:** 9.1.4
Fix unicode emstrong [demo](https://marked-website-git-fork-uzitech-fix-emstrong-unicode-markedjs.vercel.app/demo/?text=**%5B%F0%9F%A4%96%E2%94%83bot-commands%5D(https%3A%2F%2Fdiscord.com%2Fchannels%2F870575002536280074%2F981392899012980796)**%20hello&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=master)
- Fixes #3069
=> fix: fix emstrong unicode

src/Instance.ts, test/unit/instance-spec.js
**Marked version:** 9.1.5
Fix instance.lexer setting default options when none passed in.
```js
import { Marked } from 'marked';
const marked = new Marked();
marked.use({
renderer: {
heading() {
return 'test';
}
}
});
const tokens = marked.lexer('# hi');
const html = marked.parser(tokens);
```
=> fix: fix instance options sent to lexer and parser

src/marked.ts, test/types/marked.ts
**Marked version:** 10.0.0
Fix `marked` and `marked.parse` types. `async: false` could still return a `Promise<string>` if an extension sets `async: true`.
- Fixes #3101 
=> fix: fix marked types

src/Instance.ts, src/Lexer.ts, src/Tokenizer.ts, src/helpers.ts, src/rules.ts, test/types/marked.ts, test/unit/marked.test.js
**Marked version:** 10.0.0
Clean up rules so they can be easily typed.
This will be a breaking change because the rules object has changed.
=> BREAKING CHANGE: clean up rules so they can be typed

src/Hooks.ts, src/Instance.ts, src/MarkedOptions.ts, test/types/marked.ts, test/unit/Hooks.test.js
**Marked version:** 11.0.0
Add `tokens` hook that receives all tokens and can change the tokens.
This hook can allow extensions that change all tokens before walkTokens functions are called. For example an extension that adds the parent and sibling properties to tokens.
=> feat: add processAllTokens hook

src/Lexer.ts
**Marked version:** 11.1.0
Improves performance of the lexing step, specifically lexing inline elements. Prompted by this issue https://github.com/markedjs/marked/issues/2355
Create a benchmark file `bench-100.md` - this file copy pasted x 100 https://raw.githubusercontent.com/thephpleague/commonmark/2.2/tests/benchmark/sample.md (I saw that file linked in the issue and it looked good to me)
master:
- `npm run build`
- create a cpu profile with `node --cpu-prof bin/marked.js -i bench-100.md -o bench-100.html`
Apply my changes:
- `npm run build`
-  create an updated cpu profile with `node --cpu-prof bin/marked.js -i bench-100.md -o bench-100.html`
Load the two profiles in https://www.speedscope.app/ 
- before: 358ms doing marked stuff, 334ms lexing
- after: 242ms …
=> refac: improve lexing inline elements step's performance

bin/main.js, test/unit/bin.test.js
**Marked version:** 11.1.1
This PR fixes a slight bug in the `marked` CLI in which the error message due to a `ENOENT` was bugging out the error output. 
I also updated the language in the `ENOENT` error to better reflect the fact that the `ENOENT` may have been due to any of the inputted files. 
When running the `marked` CLI with an input file that does not exist, I expect it to print out an error containing only the relevant information.
Marked was attempting to print out both error paths, and attempting to print an error object to `stderr`
The stacktrace above was remediated.
=> Fix ENOENT error message in CLI

src/Instance.ts, test/unit/marked.test.js
**Marked version:** 11.1.1
Flatten custom extension childToken arrays before running them through walk tokens. This will allow custom extensions to have child tokens like the `table` token where the `rows` field is an array of arrays of tokens.
- Fixes #3170 
=> feat: flatten childToken arrays

.github/workflows/tests.yml, package.json
**Marked version:** any
Added configurations to package.json and the CI workflow, so that the GitHub Actions Workflow and semantic-release generate provenance information for this package (see https://github.com/semantic-release/npm#npm-provenance).
marked being published with verifiable Provenance data (see https://docs.npmjs.com/generating-provenance-statements)
marked package containing verifiable Provenance data
- Added publishing configuration to package.json
- Added ID Token permissions to GitHub Actions workflow
=> ci: Publish with Provenance

docs/USING_PRO.md
**Marked version:** all
- Fixes #3316.
Documentation should be explicit for new users when using Lexer.
User is now informed of different behaviors when using `marked.lexer` or `new marked.Lexer`.
n/a
=> Update Lexer section in USING_PRO.md

src/Lexer.ts, src/Tokenizer.ts, test/specs/commonmark/commonmark.0.31.json, test/specs/gfm/commonmark.0.31.json, test/unit/marked.test.js
**Marked version:** 12.0.2
Fix blockquote continuation for code blocks
Fixes [CommonMark #236](https://spec.commonmark.org/0.31.2/#example-236)
Fixes [CommonMark #237](https://spec.commonmark.org/0.31.2/#example-237)
also adds space token after blockquote and hr if there are multiple newlines. fixes #3167.
I believe this will be a breaking change since tokens will change even though the output won't change.
=> fix: blockquote code continuation

docs/USING_PRO.md, package-lock.json, src/Instance.ts, src/MarkedOptions.ts, src/Parser.ts, src/Renderer.ts, src/TextRenderer.ts, src/Tokenizer.ts, src/Tokens.ts, test/types/marked.ts, test/unit/Lexer.test.js, test/unit/Parser.test.js, test/unit/marked.test.js
**Marked version:** v12.0.2
- Send token objects to renderers and move logic to parse tokens from the parser to the renderers. 
- Fixes #2640
- Add `parser` as a property on the Renderer object
- Add space renderer that returns empty string by default
- Send block text tokens to the text renderer
- Add `header` and `align` properties to TableCell token
- Add TableRow token
- Add Checkbox token
=> feat: Send token objects to renderers

docs/USING_ADVANCED.md
Migrating from an old marked the status of option `smartLists` is not clear.
Reference #2582
Mention the option as removed.
Add to doc
Search.
=> chore(docs): add removed option `smartLists`

src/Instance.ts, src/MarkedOptions.ts, test/types/marked.ts
**Marked version:** v13
fix `this` type in renderer, tokenizer, and hooks methods
- Fixes #3326
=> fix: fix this type in extension methods

package-lock.json, package.json
add npm scripts to only run tests with `only: true` set
=> chore: add only test scripts

src/Tokenizer.ts, test/specs/new/list_with_line_break.html, test/specs/new/list_with_line_break.md
**Marked version:** v13.0.1
**Markdown flavor:** CommonMark & GitHub Flavored Markdown
- Fixes #2779
=> fix: fix list item with blank first line

src/Instance.ts, src/marked.ts, test/types/marked.ts, test/unit/marked.test.js
**Marked version:** v13
BREAKING CHANGE: throw an error if `async: false` is sent with parse options when using an async extension.
This allows us to overload the parse method when the `async ` option is set.
```js
const html: Promise<string> = marked.parse(md, { async: true });
const html: string = marked.parse(md, { async: false});
const html: Promise<string> | string = marked.parse(md);
```
closes #3116
=> fix: allow async option to dictate type returned

.gitignore, docs/USING_PRO.md, src/Hooks.ts, src/Instance.ts, src/MarkedOptions.ts, test/types/marked.ts, test/unit/Hooks.test.js
**Marked version:** 14.0.0
Add `provideLexer` and `provideParser` hooks to allow extensions that need to change the lexer or parser. This will allow adding links to the Lexer for chunked rendering (#3315). This will also allow extensions to create a new Parser to return something other than an html string. The Parser could return dom elements or react/vue/angular components.
- Fixes #3315
=> feat: add provideLexer and provideParser hooks

package.json, src/marked.ts, test/types/marked.ts
**Marked version:** 14.0.0
remove block and inline from export types. They were never actually exported. This is caused by https://github.com/timocov/dts-bundle-generator/issues/330
- Fixes #3426 
=> fix: don't export block or inline

bin/main.js
v14.1.2
Doing a Ctrl + C (^C ) caused an error on the child process spawned by marked.
The fix was to forward the signal and kill it in the spawned process. 
- Fixes https://github.com/markedjs/marked/issues/2706
Sorry for the silliest oopsie at #3482
=> fix: kill SIGINT signal at man for marked --help

src/rules.ts, test/specs/new/underscore_link.html, test/specs/new/underscore_link.md
**Marked version:** 14.1.2
Include a single set of nested parentheses in the emStrong link mask. This won't fix the issue completely but will fix for common wikipedia urls like https://en.wikipedia.org/wiki/Node_(networking)
- Fixes #3468 
=> fix: include single nested parens in emStrong link mask

README.md
It seems (per badgen/badgen.net#663) that size badge is no longer supported so it has to be removed
N/A
- Fixes a problem with broken badge in the project's readme file
There should be no broken badge in the project's readme file
There is a broken badge in the project's readme file
The broken badge was removed 🙂 
=> Remove gzip size badge

src/Tokenizer.ts, test/specs/new/html_following_list.html, test/specs/new/html_following_list.md
**Marked version:** 14.1.3
HTML comment should end list without a blank line between them
- Fixes #3515 
=> fix: fix html comment after list

src/Lexer.ts, src/Renderer.ts, src/Tokenizer.ts, src/helpers.ts, src/rules.ts
**Marked version:** 14.1.3
Move all regular expressions to rules.ts to be able to reuse similar regular expressions and spped up marked by creating the regular expressions once instead of inside a loop like the tokenizer or parser loops. These rules will be in an object exported as `other` by rules.ts. 
=> BREAKING CHANGE: Move all regexes to rules

src/rules.ts
**Marked version:** 13.0.1
- as [pr3229](https://github.com/markedjs/marked/pull/3229) said, the punctuation regex syntax is not supported in some browser
- change the string to a regular expression. Then babel can transpile it correctly.
Marked should work fine in most cases.
Host environment reports error due to unsupported regex syntax.
-->
=> fix: update punctuation regex syntax for compatibility

src/rules.ts
**Marked version:** 15.0.2
- as https://github.com/markedjs/marked/pull/3540#issuecomment-2498271390 said, the punctuation regex syntax is not correct when babel transpile.
- change the regexp, Then babel can transpile it correctly.
Marked should work fine in most cases.
Host environment reports error due to unsupported regex syntax.
https://github.com/markedjs/marked/pull/3540#issuecomment-2498573222
=> fix: update punctuation regex syntax to fix babel mistaken transpile

src/Tokenizer.ts, test/unit/marked.test.js
**Marked version:** 15.0.3
Fix looping forever when a list doesn't have any items. For example if it thinks the item is an hr but hr has been disabled like
```js
tokenizer: {
hr() {
return undefined;
}
}
```
- Fixes #3559 
=> fix: fix list with no items looping forever

api/dingus.js
found a better way to import json that works also with other engines like chrome and graalvm .....
- Fixes #### (if fixing a known issue; otherwise, describe issue using the following format)
=> Update dingus.js import json

src/rules.ts, test/specs/new/hr_following_nptables.html, test/specs/new/hr_following_nptables.md, test/specs/new/hr_following_tables.html, test/specs/new/hr_following_tables.md
**Marked version:** 15.0.6
- Fixes #3610 
=> fix: fix table rendered as heading

docs/USING_ADVANCED.md
=> docs: add marked-cjk-breaks to "Known Extensions"

src/Tokenizer.ts, src/helpers.ts, test/specs/commonmark/commonmark.0.31.2.json, test/specs/gfm/commonmark.0.31.2.json, test/specs/new/link_unbalanced.html, test/specs/new/link_unbalanced.md
**Marked version:** 15.0.8
fixes https://spec.commonmark.org/0.31.2/#example-497
Links and images with unbalanced parentheses need to be escaped
=> fix: fix link url with no closing parenthesis

src/rules.ts, test/specs/commonmark/commonmark.0.31.2.json, test/specs/gfm/commonmark.0.31.2.json
**Marked version:** 15.0.9
Allow non-breaking space in link url
fixes https://spec.commonmark.org/0.31.2/#example-507
=> fix: fix non-breaking space in link url

src/Renderer.ts, src/Tokenizer.ts, src/Tokens.ts, test/specs/commonmark/commonmark.0.31.2.json, test/specs/gfm/commonmark.0.31.2.json, test/types/marked.ts, test/unit/Lexer.test.js, test/unit/Parser.test.js, test/unit/marked.test.js
**Marked version:** 15.0.9
Image alt text should be rendered in plain text.
fixes:
- https://spec.commonmark.org/0.31.2/#example-573
- https://spec.commonmark.org/0.31.2/#example-574
- https://spec.commonmark.org/0.31.2/#example-575
- https://spec.commonmark.org/0.31.2/#example-576
- https://spec.commonmark.org/0.31.2/#example-577
- https://spec.commonmark.org/0.31.2/#example-585
- https://spec.commonmark.org/0.31.2/#example-589
=> fix: fix image alt text rendered

src/Lexer.ts, test/unit/Lexer.test.js
**Marked version:** 16.1.1
A multiline list item currently gets an extra newline in the raw property
```md
- line 1
line 2
```
Tokens:
```diff
{
type: 'list',
raw: '- line 1\n  line 2\n',
ordered: false,
start: '',
loose: false,
items: [
{
type: 'list_item',
raw: '- line 1\n  line 2',
task: false,
checked: undefined,
loose: false,
text: 'line 1\nline 2',
tokens: [{
type: 'text',
-         raw: 'line 1\n\nline 2',
+         raw: 'line 1\nline 2',
text: 'line 1\nline 2',
tokens: [{ type: 'text', raw: 'line 1\nline 2', text: 'line 1\nline 2', escaped: false }],
}],
},
],
},
```
=> fix: fix multiline list item adds extra newline to raw

src/rules.ts, test/specs/new/em_link_brackets.html, test/specs/new/em_link_brackets.md
**Marked version:** 16.3.0 / master
**Markdown flavor:** CommonMark
- Fixes #3774 
The following Markdown:
`_[`a[b]c`](http://example.com/_/path)_`
to be parsed into an emphasized link whose text is a codespan. In HTML this should be:
`<p><em><a href="http://example.com/_/path"><code>a[b]c</code></a></em></p>`
Before the change Marked produced a broken output where the emphasis was split and the link text/URL were parsed separately. The produced HTML looked like:
`<p><em>[<code>a[b]c</code>](http://example.com/</em>/path)_</p>`
Updated the em/strong masking pattern so link text that contains a codespan is treated as a single block to be skipped by the em/strong tokenizer.
- Changed the `blockSkip` regex in `marked/src/rules.ts` so bracketed link text may include backtick codespans …
=> bug: fix links with square brackets in inline code break wrapping italics

src/Instance.ts, test/unit/Hooks.test.js
**Marked version:** 16.2.1
Allow provideParser and provideLexer to be async functions.
=> feat: Add async provideParser provideLexer
