README.md

Because the new year is upon us

Update copyright to 2018 in README

---

package-lock.json
package.json

Release 0.3.14

---

.github/PULL_REQUEST_TEMPLATE.md

PR fixes relative link issue to RELEASE.md in PR template.
- Tests 
??

Fix relative link in PR Template

---

package.json

**Marked version:** ff878730cd1585f3c67c31490169615682a75c84
revert #1088 to allow passing tests
see https://github.com/markedjs/marked/pull/1088#issuecomment-370119433

revert #1088

---

docs/USING_ADVANCED.md

Just fixes link path in document.

Fix usage links in USING_ADVANCED.md ( 2nd )

---

docs/AUTHORS.md

**@mention the contributor:** @styfle 
This is a recommendation to:
@styfle has done a lot of little things that have helped improve the contributor experience (including instructing and knowledge sharing with me).
- Initial GH Pages site #1138 
- Catching little things like adding the url to the repo itself
- I have/had more and will dig them up should the need arise
If you're the one mentioned in this PR:
within 30 days (silence is consent at this point, can't have the pull requests page filled with PRs related to badges forever).
Note: All committers must approve via review before merging, the disapproving committer can simply close the PR.

styfle to admin

---

README.md

Update link to demo page in README.md

---

docs/USING_ADVANCED.md

1. Tab indent -> 2 spaces indent.
2. Rename undefined variable.
3. (The last diff is from automatically added line break at EOF).

Fix nits in code example in USING_ADVANCED.md

---

docs/USING_ADVANCED.md

Fix typo in USING_ADVANCED.md

---

docs/USING_PRO.md

The deleted fragment is a duplicate of the straight above fragment.

Remove duplicate part in docs/USING_PRO.md

---

.github/PULL_REQUEST_TEMPLATE.md

Fix typos in .github/PULL_REQUEST_TEMPLATE.md

---

docs/demo/demo.js
docs/demo/index.html
docs/demo/initial.md

Adds a way to link to the demo with given text
The URL is also updated automagically 🎉 whenever the input changes 😃 

add permalink and clear button

---

docs/USING_PRO.md

If this behavior is intended, it may need to be documented to reduce possible unexpectedness.

Document mutability of tokens argument in parser

---

docs/demo/index.html

- use `marked.js` instead of `marked.min.js` in demo to make debugging easier

use marked.js in demo

---

.github/ISSUE_TEMPLATE.md

- Add demo links to [CommonMark](https://spec.commonmark.org/dingus/) and [Marked](https://marked.js.org/demo/) in the issue template

Update ISSUE_TEMPLATE with demo links

---

man/marked.1

without the input flag the CLI errors out

Added missing input flag

---

.github/PULL_REQUEST_TEMPLATE/badges.md

This PR makes what happens after the 30 days for badge PRs. 

Clarify 30 day window on badges

---

docs/AUTHORS.md

Be more explicit in what is requested for users

---

docs/AUTHORS.md

**@mention the contributor:** @tomtheisen
See #1239 
within 30 days, if you have not indicated which option you are taking one of the following will happen:
1. If adding a badge, we will assume you are graciously declining.
2. If removing a badge, we will assume you do not want to dispute the recommendation; therefore, the badge will be removed.
Note: All committers must approve via review before merging, the disapproving committer can simply close the PR.

Defibrillator badge to tomtheisen

---

README.md

Put additional links into readme

---

docs/USING_PRO.md

- Some renderer methods have more parameters than documented. Let’s update them.

Add missing parameters for renderer methods

---

lib/marked.js

(micro PR, almost useless)
Just because I noticed it in the minified file and asked myself: "Hey, is this lib abandoned?"

Update copyright in source code

---

docs/AUTHORS.md

I want to nominate @UziTech to Publisher status.
I believe @UziTech is the most active member of this project and it will be valuable to have someone who is readily available and also very knowledgeable of the code who can also publish to npm.
within 30 days, if you have not indicated which option you are taking one of the following will happen:
1. If adding a badge, we will assume you are graciously declining.
2. If removing a badge, we will assume you do not want to dispute the recommendation; therefore, the badge will be removed.
Note: All committers must approve via review before merging, the disapproving committer can simply close the PR.

Add release badge to Tony Brix

---

man/marked.1.txt

Follows-up ec78260e116 / #1118.

man: Update bugs url in text version

---

docs/demo/demo.js
docs/demo/index.html

Demo selector Enhancement requested in #1406 
@styfle can you please take a look and please help me understand what the Snyk issue might be?

Add select option in demo mode to choose Marked version

---

package-lock.json
package.json

Release v0.6.3

---

package-lock.json
package.json

remove `module` field in `package.json`
see discussion https://github.com/markedjs/marked/pull/1571#issuecomment-562891963

remove module field

---

bin/marked

https://github.com/markedjs/marked/issues/1587

marked --help

---

docs/demo/worker.js

Fix lexer data in demo
```markdown
| a | b |
|---|---|
| 1 | 2 |
| 3 | 4 |
```
[current demo](https://marked.js.org/demo/?outputType=lexer&text=%7C%20a%20%7C%20b%20%7C%0A%7C---%7C---%7C%0A%7C%201%20%7C%202%20%7C%0A%7C%203%20%7C%204%20%7C&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&versio …

fix demo table tokens

---

src/Parser.js
test/specs/new/list_loose_tasks.html
test/specs/new/list_loose_tasks.md

**Marked version:** 1.0.0
Fix loose task list when task item has no text.
[demo](https://marked.js.org/demo/?text=%20%20-%20%5B%20%5D%20checklist%20item%0A%0A%20%20-%20%5B%20%5D%20&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=ma …

fix loose task list with no tokens

---

docs/index.html

Fix docs showing 404 on https://marked.js.org/#/USING_PRO.md%23renderer
- Fixes https://github.com/markedjs/marked/issues/1707#issuecomment-643673264
test: https://markedjs-git-fork-uzitech-hash-hash.markedjs.vercel.app/#/USING_PRO.md%23renderer

decode hash in docs

---

docs/demo/quickref.md

Fix a few issues with quick reference docs.
[Old](https://marked.js.org/demo/?outputType=quickref)
[New](https://markedjs-git-fork-uzitech-quick-ref.markedjs.vercel.app/demo/?outputType=quickref)
- Closes #1682 

Fix quick ref

---

SECURITY.md

**@mention the contributor:**
If it weren't for @UziTech, none of us would still be here - at least not begrudgingly. He has done wonders over the past 2+ years in improving the developer experience around here.
Not just in the tech and tools department - though that's pretty awesome - but also in the leading by example and helping ensure a non-toxic environment. We have seen so many commits and chip-ins from the community since he...inspired...me loosen the rock. Since then, it's been wonderful to see what talented, empowered people can do when contributing in the areas they want to.
(Sorry I didn't realize you weren't already an owner.)
Thanks...for everything. Personally, I've grown a lot thanks to Marked, and it wouldn't have happened without you.
within 30 days, if you have not …

Org. owner to UziTech

---

src/rules.js
test/specs/new/indented_tables.html
test/specs/new/indented_tables.md

**Marked version:** 1.1.1
fixes indented table rows to act like code blocks instead of table rows.
- Fixes #1747

fix indented tables to follow gfm spec

---

docs/demo/demo.css
docs/demo/index.html

Add links to the CommonMark and Daring Fireball demos from our demo page so it is easy to compare.

chore(demo): add links to other demos

---

docs/USING_PRO.md
docs/_document.html

**Marked version:** docs
Add `extensions` link to navigation links
[/using_pro#extensions](https://markedjs-git-fork-uzitech-extensions-link-markedjs.vercel.app/using_pro#extensions)

chore(docs): add extensions link to nav links

---

docs/USING_ADVANCED.md

**Marked version:** docs
fixes async highlight example to include calling marked with a callback.

chore(docs): fix async highlight example

---

src/rules.js
test/specs/new/space_after_table.html
test/specs/new/space_after_table.md

**Marked version:** v3.0.2
**Markdown flavor:** GFM
Fix ignore space after table line.
- Fixes #2196

fix: fix space at end of table line

---

src/rules.js

This PR is for releasing #2203 
fixes #2202

fix: fix detection of orphaned emStrong delimiters

---

docs/USING_PRO.md

remove nptable tokenizer from docs since it was removed in v3

chore(docs): remove nptable tokenizer from docs

---

bin/marked.js

**Marked version:** v4.0.3
Fix cli
- Fixes #2268

fix: fix cli

---

README.md
docs/INDEX.md

I tried to improve examples for what concerns CLI usages, which are not very clear.
I wanted also to compare Options from Advanced Usage with the one specified in the man file, but I wasn't able to understand quickly if all the options that can be set both through Node.JS API and CLI or if some are valid for CLI and others only for node.js (e.g. baseUrl). Let me know if I can improve also this aspect.
Let me know if I can change or if you don't like something. Thank you!

chore(docs): Improved CLI Examples

---

src/Tokenizer.js
test/specs/new/list_item_unindented_asterisk.html
test/specs/new/list_item_unindented_asterisk.md
test/specs/run-spec.js

Fixes #1980 
as described in the [thread](https://github.com/markedjs/marked/issues/1980#issuecomment-1080495730).
This makes marked behave like commonmark. Test is added to ensure it properly works, and nothing else fails.
```markdown
---
pedantic: true
headerIds: false
---
+ list1
+Not list(without space)
- list2
- list1
-Not list(without space)
- list2
1. list
1.Notlist(without space)
1. list
```

fix: list item bullet without whitespace

---

README.md
docs/INDEX.md

**Marked version:** 4.0.15
Marked was part of a CTF challenge of the [ångstromCTF](https://angstromctf.com/).
The goal was to find an XSS that bypasses marked in combination with DOMPurify.
Since DOMPurify only sanitized the input of marked, an XSS was possible ([Writeup](https://infosecwriteups.com/clique-writeup-%C3%A5ngstromctf-2022-e7ae871eaa0e)).
A quick [GitHub search](https://github.com/search?p=2&q=marked.parse%28DOMPurify.sanitize&type=Code) relieved that such examples of wrong marked/DOMPurify usage exist ([Example 1](https://github.com/jonasholbech/svelte-uikit/blob/581d8d403d7b3c4d41ddd7aaf795c3935ebed0e2/src/utils/render.js), [Example 2](https://github.com/Prince2300/Moscow-State-University/blob/9b416ca85763e60b4461864df26c9f35e62e85f9/Teacher.js), ...).
I think, the marked …

Add a secure example to the Docu.

---

docs/INDEX.md

docs: add js-xss to sanitizer warning

---

README.md

Documentation update
This PR will make the installation commands for CLI and browser clickable and copiable to clipboard.

chore(docs): Update installation instructions

---

src/Tokenizer.js
test/specs/new/list_code_header.html
test/specs/new/list_code_header.md

**Marked version:** 4.0.17
fix header in list item.
[marked demo](https://marked.js.org/demo/?text=-%20list%0A%20%20%23%20header&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=4.0.17)
[commonmark …

fix: fix heading in list item

---

docs/AUTHORS.md

rtnF md : Markdown-based anonymous blogging platform
https://md.altilunium.my.id

Add new Users : rtnF md

---

docs/AUTHORS.md

- Fixes outdated link in the doc

Update outdated link

---

docs/demo/worker.js

Merge the options given in the demo with the default options. This will make it easier to change options in the demo without needing to specify all options.

merge demo options with defaults

---

.github/workflows/tests.yml

- Add build test to ci to make sure that works on PRs.
- Use actions/setup-node instead of nvm to install node versions in ci.
- Skip is no longer needed in ci github actions does it by default.

chore(ci): update ci

---

docs/USING_PRO.md

**Marked version:** 4.2.12
- Fixes #1484

docs: Explain how to get an instance of `Slugger`

---

docs/USING_PRO.md

- Fixes [Issue 2669](https://github.com/markedjs/marked/issues/2669) by documenting the difference between adding and editing extensions.

chore(docs): Modify Extension Docs

---

rollup.config.js

**Marked version:** 9.0.0
fix the version comment in marked.min.js
- Fixes #2975

chore: add version and copyright to marked.min.js

---

src/Tokenizer.ts
src/rules.ts
test/specs/new/table_vs_setext.html
test/specs/new/table_vs_setext.md

**Marked version:** 9.0.0
Fix single column table without pipe.
- Fixes #1499

fix: single column table

---

bin/main.js

**Marked version:** v9.0.2
marked.1.txt was changed to marked.1.md in v9
- Fixes #2990 

fix: marked --help

---

SECURITY.md

- Update authors link in SECURITY.md (the current link is sending to the homepage of the project)

docs: Update authors link in SECURITY.md

---

test/helpers/load.js

Remove node 4 polyfills from tests

chore: remove node 4 polyfills

---

README.md

- Fixes #### (if fixing a known issue; otherwise, describe issue using the following format)

docs: Correcting links to documentation

---

README.md
docs/INDEX.md

Add docs for using esm in the browser.
- Fixes #2719

docs: add docs for esm in browser

---

CHANGELOG.md

Add changelog that points to the releases.
Many people have mentioned marked not having a changelog because they don't know about the release notes.

chore: add changelog that points to releases

---

src/Tokenizer.ts
src/rules.ts
test/specs/commonmark/commonmark.0.31.json
test/specs/gfm/commonmark.0.31.json
test/specs/new/blockquote_setext.html
test/specs/new/blockquote_setext.md
test/specs/new/setext_no_blankline.html
test/specs/new/setext_no_blankline.md

**Marked version:** 12.0.1
- Fixes #3217

fix: fix Setext continuation in blockquote

---

api/dingus.js

Fix dingus for babelmark
works: https://marked-website-git-fork-uzitech-dingus-markedjs.vercel.app/api/dingus?text=*test*

fix dingus import

---

docs/USING_PRO.md

**Marked version:** v13
- Fixes #3338

docs: add useNewRenderer note

---

docs/USING_PRO.md

Fix docs example to match new renderer
- Fixes #3390

docs: fix heading renderer example

---

package-lock.json
package.json

chore: update testutils to v14.1.1-0

---

src/Tokenizer.ts
test/specs/new/html_following_list.html
test/specs/new/html_following_list.md

**Marked version:** 14.1.1
HTML block should interrupt list 
- Fixes #3437

fix: fix html following list

---

docs/INDEX.md

marked_reader source code: https://github.com/CNOCTAVE/marked_reader
marked_reader docs: https://cnoctave.github.io/marked_reader/index.html

Add a List of Tools Using Marked

---

docs/USING_PRO.md

Add marked extensions template to the custom extension docs

docs: Marked extension template docs

---

package.json

**Marked version:** 15.0.6
fix npm package.json repository for newer npm

chore: fix pkg repository
